using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

// Transparent structural evidence, not a maintainability score or release verdict. See #1940.
if (args.Length == 0 || args[0] is not ("capture" or "compare" or "self-test"))
    throw new ArgumentException("Usage: capture ROOT OUTPUT | compare BEFORE AFTER OUTPUT [CHANGED_SYMBOLS.json] | self-test");
if (args[0] == "capture" && args.Length != 3 || args[0] == "compare" && args.Length is not (4 or 5) || args[0] == "self-test" && args.Length != 1)
    throw new ArgumentException("Usage: capture ROOT OUTPUT | compare BEFORE AFTER OUTPUT [CHANGED_SYMBOLS.json] | self-test");
if (args[0] == "self-test") { SelfTest(); return; }
if (args[0] == "capture")
{
    var report = Build(Path.GetFullPath(args[1]));
    File.WriteAllText(args[2], JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true }) + "\n", new UTF8Encoding(false));
    return;
}
var before = JsonSerializer.Deserialize<Report>(File.ReadAllText(args[1]))!;
var after = JsonSerializer.Deserialize<Report>(File.ReadAllText(args[2]))!;
var selected = args.Length > 4 ? ChangedKeys(args[4]) : null;
var delta = Compare(before, after, selected);
File.WriteAllText(args[3], JsonSerializer.Serialize(delta, new JsonSerializerOptions { WriteIndented = true }) + "\n", new UTF8Encoding(false));
static string Hash(string value) => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(value)));
static bool HasGeneratedHeader(string source)
{
    // Only leading comment trivia is a header; code/literals and directives
    // terminate the header region. See #1939.
    var trivia = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.CSharp14)).GetRoot().GetFirstToken(includeZeroWidth: true).LeadingTrivia;
    foreach (var item in trivia)
    {
        if (item.IsKind(SyntaxKind.WhitespaceTrivia) || item.IsKind(SyntaxKind.EndOfLineTrivia)) continue;
        if (item.Kind() is not (SyntaxKind.SingleLineCommentTrivia or SyntaxKind.MultiLineCommentTrivia
            or SyntaxKind.SingleLineDocumentationCommentTrivia or SyntaxKind.MultiLineDocumentationCommentTrivia)) return false;
        if (item.ToFullString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) return true;
    }
    return false;
}
static string Git(string root, params string[] arguments)
{
    var start = new ProcessStartInfo("git") { WorkingDirectory = root, RedirectStandardOutput = true, RedirectStandardError = true };
    foreach (var argument in arguments) start.ArgumentList.Add(argument);
    using var process = Process.Start(start)!;
    var output = process.StandardOutput.ReadToEnd(); var error = process.StandardError.ReadToEnd(); process.WaitForExit();
    if (process.ExitCode != 0) throw new InvalidOperationException(error);
    return output;
}
static Report Build(string root)
{
    var tracked = Git(root, "ls-files", "-z").Split('\0', StringSplitOptions.RemoveEmptyEntries).Order(StringComparer.Ordinal);
    var projects = tracked.Where(path => path.EndsWith(".csproj", StringComparison.Ordinal)).ToArray();
    using var scope = JsonDocument.Parse(File.ReadAllText(Path.Combine(root, "architecture/repository-scope.json")));
    var rows = new List<Metric>(); var exclusions = new List<Exclusion>(); var inputHashes = new List<InputHash>();
    foreach (var path in tracked.Where(path => path.EndsWith(".cs", StringComparison.Ordinal)))
    {
        var full = Path.Combine(root, path);
        if (!File.Exists(full)) throw new InvalidOperationException($"Tracked input missing: {path}");
        var source = File.ReadAllText(full).Replace("\r\n", "\n").Replace('\r', '\n');
        var project = projects.Where(p => path.StartsWith(p[..(p.LastIndexOf('/') + 1)], StringComparison.Ordinal))
            .OrderByDescending(p => p.LastIndexOf('/')).ThenBy(p => p, StringComparer.Ordinal).FirstOrDefault();
        var classification = "shipping"; string? exclusion = null;
        foreach (var groupName in new[] { "excludedRoots", "reviewOnlyRoots" })
        foreach (var rule in scope.RootElement.GetProperty(groupName).EnumerateArray())
        {
            var prefix = rule.GetProperty("path").GetString()!;
            if (path == prefix || path.StartsWith(prefix + "/", StringComparison.Ordinal)
                || (prefix is "bin" or "obj" && path.Split('/').Contains(prefix)))
            { classification = rule.GetProperty("classification").GetString()!; exclusion = rule.GetProperty("reason").GetString(); }
        }
        if (project is null && exclusion is null) { classification = "unowned"; exclusion = "No tracked ancestor project."; }
        if (exclusion is null)
        {
            foreach (var rule in scope.RootElement.GetProperty("projectRules").EnumerateArray())
                if (System.Text.RegularExpressions.Regex.IsMatch(project!, "^" + System.Text.RegularExpressions.Regex.Escape(rule.GetProperty("pattern").GetString()!).Replace("\\*", ".*") + "$", System.Text.RegularExpressions.RegexOptions.CultureInvariant))
                { classification = rule.GetProperty("classification").GetString()!; break; }
            if (path.EndsWith(".g.cs", StringComparison.Ordinal) || path.EndsWith(".generated.cs", StringComparison.Ordinal) || HasGeneratedHeader(source))
            { classification = "generated"; exclusion = "Generated filename or auto-generated header."; }
        }
        inputHashes.Add(new(path, Hash(source), project, classification));
        if (exclusion is not null) { exclusions.Add(new(path, classification, exclusion)); continue; }
        var tree = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.CSharp14), path);
        if (tree.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error)) throw new InvalidOperationException($"Syntax errors in {path}; refusing partial evidence.");
        var compilation = CSharpCompilation.Create("StructuralEvidence", new[] { tree },
            new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });
        rows.AddRange(FileMetrics(tree.GetRoot(), compilation.GetSemanticModel(tree), project!, classification, path));
    }
    var sdk = Process.Start(new ProcessStartInfo("dotnet", "--version") { WorkingDirectory = root, RedirectStandardOutput = true })!;
    var sdkVersion = sdk.StandardOutput.ReadToEnd().Trim(); sdk.WaitForExit();
    return new(1, "Excise.StructuralEvidence/2", "Microsoft.CodeAnalysis.CSharp package 5.3.0; assembly " + typeof(CSharpCompilation).Assembly.GetName().Version,
        sdkVersion, "CSharp14; no MSBuild evaluation or preprocessor symbols; single-file core-library binding only for direct recursion",
        "Tracked *.cs under nearest tracked *.csproj; LF-normalized UTF-8 SHA-256; excludes repository-scope excludedRoots/reviewOnlyRoots, generated files/headers, unowned files, and untracked files.",
        Complexity.Contract + "; " + Complexity.Definitions + " Supported limits: " + Complexity.Limits,
        "dotnet run --project tools/Excise.StructuralEvidence -- capture . OUT.json", inputHashes.ToArray(), exclusions.OrderBy(x => x.Path, StringComparer.Ordinal).ToArray(),
        rows.OrderBy(x => x.Key, StringComparer.Ordinal).ThenBy(x => x.Path, StringComparer.Ordinal).ThenBy(x => x.StartLine).ToArray());
}
static Metric[] FileMetrics(SyntaxNode rootNode, SemanticModel model, string project, string classification, string path)
{
    var rows = new List<Metric>();
    var fileRows = new List<(SyntaxNode Declaration, Metric Row)>();
    foreach (var declaration in rootNode.DescendantNodes().Where(n => Complexity.Body(n) is not null))
    {
        if (declaration is LocalFunctionStatementSyntax && !declaration.Ancestors().Any(n =>
            n is not LocalFunctionStatementSyntax && Complexity.Body(n) is not null)) continue;
        var symbol = model.GetDeclaredSymbol(declaration); var body = Complexity.Body(declaration);
        if (symbol is null || body is null) continue;
        var (cyclomatic, cognitive, maxNesting) = Complexity.Measure(body, model, symbol);
        var span = declaration.GetLocation().GetLineSpan();
        var symbolKey = project + "::" + DeclarationId(declaration, model);
        var startLine = span.StartLinePosition.Line + 1;
        var kind = declaration switch { LocalFunctionStatementSyntax => "local-function", AccessorDeclarationSyntax => "accessor",
            PropertyDeclarationSyntax or IndexerDeclarationSyntax => "property", _ => "method" };
        var parameters = symbol switch { IMethodSymbol m => m.Parameters.Length, IPropertySymbol p => p.Parameters.Length, _ => 0 };
        var row = new Metric(symbolKey + "@" + path + ":" + startLine, symbolKey, kind, symbol.ToDisplayString(), project, classification,
            path, startLine, span.EndLinePosition.Line + 1, cyclomatic, cognitive, maxNesting,
            Complexity.ExecutableLines(body), parameters, symbol.DeclaredAccessibility.ToString());
        fileRows.Add((declaration, row)); rows.Add(row);
    }
    foreach (var type in rootNode.DescendantNodes().OfType<TypeDeclarationSyntax>())
    {
        var symbol = model.GetDeclaredSymbol(type); if (symbol is null) continue;
        var members = fileRows.Where(x => x.Declaration.Ancestors().OfType<TypeDeclarationSyntax>().FirstOrDefault() == type)
            .Select(x => x.Row).ToArray();
        var span = type.GetLocation().GetLineSpan();
        var symbolKey = project + "::" + (symbol.GetDocumentationCommentId() ?? symbol.ToDisplayString());
        var startLine = span.StartLinePosition.Line + 1;
        rows.Add(new(symbolKey + "@" + path + ":" + startLine, symbolKey, "type", symbol.ToDisplayString(), project, classification,
            path, startLine, span.EndLinePosition.Line + 1,
            members.Sum(m => m.Cyclomatic), members.Sum(m => m.Cognitive), members.Select(m => m.MaxNesting).DefaultIfEmpty(0).Max(),
            members.Sum(m => m.ExecutableLines), 0, symbol.DeclaredAccessibility.ToString()));
    }
    return rows.ToArray();
}
static string DeclarationId(SyntaxNode declaration, SemanticModel model)
{
    var symbol = model.GetDeclaredSymbol(declaration)!;
    if (declaration is LocalFunctionStatementSyntax local)
    {
        var owner = local.Ancestors().First(n => Complexity.Body(n) is not null);
        var siblings = owner.DescendantNodes(n => n is not LocalFunctionStatementSyntax || n == local)
            .OfType<LocalFunctionStatementSyntax>().Where(n => n.Identifier.ValueText == local.Identifier.ValueText).ToArray();
        return DeclarationId(owner, model) + "/local:" + symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
            + "#" + Array.IndexOf(siblings, local);
    }
    if (declaration is AccessorDeclarationSyntax accessor)
        return DeclarationId(accessor.Parent!.Parent!, model) + "/" + accessor.Keyword.ValueText;
    return symbol.GetDocumentationCommentId() ?? symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}
static string[]? ChangedKeys(string path)
{
    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    return doc.RootElement.GetProperty("Changed").EnumerateArray().Select(x => x.GetString()!).Order(StringComparer.Ordinal).ToArray();
}
static Delta Compare(Report before, Report after, string[]? selected)
{
    if (before.SchemaVersion != after.SchemaVersion || before.ToolVersion != after.ToolVersion || before.AnalyzerVersion != after.AnalyzerVersion
        || before.DotnetSdkVersion != after.DotnetSdkVersion || before.ParseContract != after.ParseContract
        || before.MetricDefinitions != after.MetricDefinitions || before.InputsAndExclusions != after.InputsAndExclusions)
        throw new InvalidOperationException("Incompatible structural metric contracts; recapture both reports with the same tool, analyzer, parse and scope contracts.");
    var old = before.Metrics.ToDictionary(x => MatchKey(x), x => x); var current = after.Metrics.ToDictionary(x => MatchKey(x), x => x);
    var keys = old.Keys.Union(current.Keys, StringComparer.Ordinal).Where(k => selected is null || selected.Any(s =>
        (old.GetValueOrDefault(k)?.SymbolKey ?? current.GetValueOrDefault(k)!.SymbolKey) is var symbol &&
        (symbol == s || symbol.StartsWith(s + "/local:", StringComparison.Ordinal)))).Order(StringComparer.Ordinal);
    var rows = new List<Change>();
    foreach (var key in keys)
    {
        old.TryGetValue(key, out var a); current.TryGetValue(key, out var b);
        if (a != null && b != null && a == b) continue;
        rows.Add(new(b?.Key ?? a!.Key, a is null ? "added" : b is null ? "removed" : "changed", a, b));
    }
    return new(1, "Exact SymbolKey plus path (partial declaration identity), independent of start line; unmatched renames/moves are removed+added. Local keys include lexical owner/signature/name ordinal. ChangedSymbols uses the Changed array from #1939; selecting an owning callable also selects its local-function rows.", rows.ToArray());
}
static string MatchKey(Metric metric) => metric.SymbolKey + "@" + metric.Path;
static void SelfTest()
{
    foreach (var source in new[] { "class Marker { string Text = \"<auto-generated/>\"; }", "class Marker {} // <auto-generated/>", "#nullable enable\n// <auto-generated/>\nclass Marker {}" })
        if (HasGeneratedHeader(source)) throw new Exception("Non-header generated marker excluded source.");
    foreach (var source in new[] { " \n// license\n// <auto-generated/>\nclass Marker {}", "/* <AUTO-GENERATED> */\nclass Marker {}" })
        if (!HasGeneratedHeader(source)) throw new Exception("Leading generated comment header missed.");
    var cases = new (string Name, string Members, int Cyclomatic, int Cognitive, int Nesting)[]
    {
        ("straight", "int F(int x) { return x; }", 1, 0, 0),
        ("root ternary", "int F(int x) => x > 0 ? 1 : 0;", 2, 1, 1),
        ("root switch", "int F(int x) => x switch { 0 => 0, 1 => 1, _ => 2 };", 4, 1, 1),
        ("statement switch", "int F(int x) { switch(x) { case 0: case 1: return 1; default: return 2; } }", 3, 1, 1),
        ("pattern labels and guards", "int F(int x) { switch(x) { case > 0 when x < 5: return 1; case 0: return 0; default: return 2; } }", 3, 1, 1),
        ("root boolean chain", "bool F(bool a, bool b, bool c) => a && b && c;", 3, 1, 0),
        ("Boolean mixed runs", "bool F(bool a, bool b, bool c, bool d) => a && b || c && d;", 4, 3, 0),
        ("Boolean parentheses", "bool F(bool a, bool b, bool c) => a && (b && c);", 3, 1, 0),
        ("Boolean independent arguments", "bool F(bool a, bool b, bool c, bool d) => G(a && b, c && d); bool G(bool a, bool b) => a;", 3, 2, 0),
        ("Boolean negation boundary", "bool F(bool a, bool b, bool c) => a && !(b && c);", 3, 2, 0),
        ("Boolean nested structural", "int F(bool a, bool b, bool c) { if(a && b && c) { while(a || b) { return 1; } } return 0; }", 6, 5, 2),
        ("pattern runs", "bool F(int x) => x is > 0 and < 10 or 20;", 3, 2, 0),
        ("pattern parentheses", "bool F(int x) => x is > 0 and (< 10 and not 5);", 3, 1, 0),
        ("null shorthand", "string F(string x) { x ??= \"x\"; return x?.ToString() ?? \"\"; }", 4, 0, 0),
        ("else-if flat chain", "int F(int x) { if(x > 0) return 1; else if(x < 0) return -1; else return 0; }", 3, 3, 1),
        ("else nested body", "int F(int x) { if(x > 0) return 1; else { if(x < 0) return -1; } return 0; }", 3, 4, 2),
        ("nested if loop", "int F(int x) { if(x > 0) { for(int i=0;i<x;i++) { if(i>2) return i; } } return 0; }", 4, 6, 3),
        ("sibling nesting reset", "int F(int x) { if(x > 0) { if(x > 1) return 1; } if(x < 0) return -1; return 0; }", 4, 4, 2),
        ("try catch finally", "int F(int x) { try { if(x > 0) return 1; } catch(System.Exception) { if(x < 0) return -1; } finally { if(x == 0) x++; } return 0; }", 4, 5, 2),
        ("catch filter Boolean", "void F(bool a, bool b) { try {} catch(System.Exception) when(a && b) {} }", 2, 2, 1),
        ("while do foreach", "void F(int[] xs) { while(false) {} do {} while(false); foreach(var x in xs) {} }", 4, 3, 1),
        ("foreach deconstruction", "void F((int,int)[] xs) { foreach(var (a,b) in xs) { if(a>b) {} } }", 3, 3, 2),
        ("nested switch", "int F(int x) { if(x>0) { switch(x) { case 1: if(x>1) return 1; break; default: break; } } return 0; }", 4, 6, 3),
        ("goto fundamental", "void F(bool a) { if(a) goto end; end: return; }", 2, 2, 1),
        ("ordinary jumps", "void F(bool a) { while(a) { if(a) break; continue; } return; }", 3, 3, 2),
        ("direct recursion once", "int F(int x) => F(x-1) + F(x-2);", 1, 1, 0),
        ("this recursion", "int F(int x) => this.F(x-1);", 1, 1, 0),
        ("generic recursion", "T F<T>(T x) => F<T>(x);", 1, 1, 0),
        ("overload is not recursion", "int F(int x) => F(\"x\"); int F(string x) => 0;", 1, 0, 0),
        ("other receiver is not recursion", "int F(int x) => new Y().F(x);", 1, 0, 0),
        ("local excluded from owner", "int F(int x) { int L(int y) { if(y > 0) return 1; return 0; } return L(x); }", 1, 0, 0),
        ("nested locals excluded", "int F(int x) { if(x > 0) { int L(int y) { int N(int z) => z>0 ? z : 0; return N(y); } return L(x); } return 0; }", 2, 1, 1),
        ("lambda nesting", "void F() { System.Func<int,int> f = x => x>0 ? x : 0; }", 2, 2, 2),
        ("anonymous method nesting", "void F() { System.Action f = delegate { if(true) {} }; }", 2, 2, 2),
        ("expression constructor", "X(bool x) => G(x ? 1 : 0); void G(int x) {}", 2, 1, 1),
        ("expression property", "int P => true ? 1 : 0;", 2, 1, 1),
        ("expression indexer", "int this[int x] => x>0 ? 1 : 0;", 2, 1, 1),
        ("expression accessor", "int P { get => true ? 1 : 0; }", 2, 1, 1),
        ("high nested fixture", "int F(int x) { " + string.Concat(Enumerable.Repeat("if(x>0) {", 10)) + "return 1;" + new string('}', 10) + "return 0; }", 11, 55, 10),
    };
    foreach (var fixture in cases)
    {
        var (root, model) = ParseFixture("class X { " + fixture.Members + " } class Y { public int F(int x) => x; }");
        var declaration = root.DescendantNodes().First(n => Complexity.Body(n) is not null);
        var body = Complexity.Body(declaration)!;
        var actual = Complexity.Measure(body, model, model.GetDeclaredSymbol(declaration)!);
        if (actual != (fixture.Cyclomatic, fixture.Cognitive, fixture.Nesting))
            throw new Exception($"{fixture.Name}: expected {(fixture.Cyclomatic, fixture.Cognitive, fixture.Nesting)}, actual {actual}.");
        if (actual != Complexity.Measure(body, model, model.GetDeclaredSymbol(declaration)!))
            throw new Exception($"{fixture.Name}: non-deterministic measure.");
    }
    var (localRoot, localModel) = ParseFixture("class X { int F(int x) { if(x>0) { int L(int y) => y>0 ? L(y-1) : 0; return L(x); } return 0; } int G() { int L(int y) => y; return L(0); } }");
    var locals = localRoot.DescendantNodes().OfType<LocalFunctionStatementSyntax>().ToArray();
    if (Complexity.Measure(Complexity.Body(locals[0])!, localModel, localModel.GetDeclaredSymbol(locals[0])!) != (2, 2, 1))
        throw new Exception("Local function nesting reset/direct recursion failed.");
    if (DeclarationId(locals[0], localModel) == DeclarationId(locals[1], localModel))
        throw new Exception("Local keys collide across owners.");
    var (typeRoot, typeModel) = ParseFixture("class X { int F() { int L(int x) => x>0 ? 1 : 0; return L(0); } class Y { int G(bool b) => b ? 1 : 0; } }");
    var collected = FileMetrics(typeRoot, typeModel, "P", "shipping", "Fixture.cs");
    var outer = collected.Single(m => m.Kind == "type" && m.Symbol == "X");
    var inner = collected.Single(m => m.Kind == "type" && m.Symbol == "X.Y");
    if ((outer.Cyclomatic, outer.Cognitive, outer.MaxNesting) != (3, 1, 1) ||
        (inner.Cyclomatic, inner.Cognitive, inner.MaxNesting) != (2, 1, 1))
        throw new Exception("Type aggregates double-counted local bodies or nested types.");
    var (topLevelRoot, topLevelModel) = ParseFixture("int F() { int L() => 1; return L(); }");
    if (FileMetrics(topLevelRoot, topLevelModel, "P", "tool", "TopLevel.cs").Length != 0)
        throw new Exception("Out-of-scope top-level functions entered isolated callable evidence.");
    var (lineRoot, _) = ParseFixture("class X { int F() {\n int L() {\n return 1;\n }\n return L();\n } }");
    if (Complexity.ExecutableLines(lineRoot.DescendantNodes().OfType<MethodDeclarationSyntax>().Single().Body!) != 1)
        throw new Exception("Local statements leaked into executable-line count.");
    var (expressionRoot, _) = ParseFixture("class X { int F() => 1; }");
    if (Complexity.ExecutableLines(Complexity.Body(expressionRoot.DescendantNodes().OfType<MethodDeclarationSyntax>().Single())!) != 1)
        throw new Exception("Expression root executable line missed.");
    var oldMetric = new Metric("P::M:X.F@Fixture.cs:1", "P::M:X.F", "method", "X.F", "P", "shipping", "Fixture.cs", 1, 1, 1, 0, 0, 1, 1, "Public");
    var newMetric = oldMetric with { Cyclomatic = 3 };
    var baseline = new Report(1, "tool", "analyzer", "sdk", "parse", "inputs", "definitions", "command", [], [], [oldMetric]);
    var current = baseline with { Metrics = [newMetric] };
    if (Compare(baseline, current, ["P::M:X.F"]).Changes.Length != 1 || Compare(baseline, current, ["P::M:Other.G"]).Changes.Length != 0)
        throw new Exception("Changed-symbol selection or delta comparison failed.");
    var shifted = baseline with { Metrics = [oldMetric with { Key = "P::M:X.F@Fixture.cs:2", StartLine = 2, EndLine = 2 }] };
    if (Compare(baseline, shifted, null).Changes is not [{ Status: "changed" }]) throw new Exception("Line shift lost declaration identity.");
    var localMetric = oldMetric with { Key = "P::M:X.F/local:L#0@Fixture.cs:1", SymbolKey = "P::M:X.F/local:L#0", Kind = "local-function" };
    if (Compare(baseline with { Metrics = [] }, baseline with { Metrics = [localMetric] }, ["P::M:X.F"]).Changes.Length != 1)
        throw new Exception("Owning changed-symbol selection omitted local row.");
    try { Compare(baseline, baseline with { ToolVersion = "different" }, null); throw new Exception("Incompatible tool contract accepted."); }
    catch (InvalidOperationException) { }
    Console.WriteLine($"PASS: {cases.Length} exact metric goldens; isolated/local recursion and identity, executable-line ownership, deterministic measurement, contract rejection and changed-symbol deltas.");
}
static (SyntaxNode Root, SemanticModel Model) ParseFixture(string source)
{
    var tree = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.CSharp14));
    if (tree.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error)) throw new Exception("Invalid golden syntax.");
    var compilation = CSharpCompilation.Create("Golden", [tree], [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
    return (tree.GetRoot(), compilation.GetSemanticModel(tree));
}
record InputHash(string Path, string Sha256, string? Project, string Classification);
record Exclusion(string Path, string Classification, string Reason);
record Metric(string Key, string SymbolKey, string Kind, string Symbol, string Project, string Classification, string Path, int StartLine, int EndLine, int Cyclomatic, int Cognitive, int MaxNesting, int ExecutableLines, int ParameterCount, string Accessibility);
record Report(int SchemaVersion, string ToolVersion, string AnalyzerVersion, string DotnetSdkVersion, string ParseContract, string InputsAndExclusions, string MetricDefinitions, string Reproduce, InputHash[] Inputs, Exclusion[] Exclusions, Metric[] Metrics);
record Change(string Key, string Status, Metric? Before, Metric? After);
record Delta(int SchemaVersion, string MatchContract, Change[] Changes);
