#!/usr/bin/env python3
"""#1374 — the registry of everything a person can DO to the GUI.

WHY THIS EXISTS
---------------
`PdfCommandIds` lists 91 command identifiers and `PdfCommandRegistry` describes
them for automation, but neither says how a human reaches one. A command with no
menu item, no shortcut and no button is unreachable; a menu item with no command
id cannot be driven by any automation surface. Both have shipped. #1308's Sign
Document existed, was tested, and no production code could reach it.

So this catalogues the INTERACTION, not the capability: every menu item, every
keyboard shortcut, every toolbar button and every mouse gesture the viewer
handles, each joined to the command id it invokes when there is one.

It is the input to the AppleScript terminology (#1281) and to the GUI test suite
that exercises the surface: a scriptable verb per interaction, generated rather
than hand-listed, so a control added to the XAML joins the scriptable surface and
the test matrix on the day it is added instead of drifting out of both.

OUTPUT
------
`tests/gui-interaction-registry.json`, regenerated by
`scripts/check-gui-interaction-registry.sh` and diffed against the tree, like
every other registry in this repo.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
XAML = ROOT / "Excise.App/Views/MainWindow.axaml"
IDS = ROOT / "Excise.Core/Automation/PdfCommandIds.cs"
OUT = ROOT / "tests/gui-interaction-registry.json"

AVALONIA_NS = "{https://github.com/avaloniaui}"
ACCESS_CMD = "CommandAccessibility.CommandId"


def strip_ns(tag: str) -> str:
    return tag.split("}", 1)[1] if "}" in tag else tag


def command_of(el) -> str | None:
    """The bound command name, e.g. Command="{Binding OpenFileCommand}" -> OpenFileCommand."""
    raw = el.get("Command")
    if not raw:
        return None
    m = re.search(r"\{Binding\s+([A-Za-z0-9_.]+)", raw)
    return m.group(1) if m else raw.strip()


def command_id_of(el) -> str | None:
    for key, value in el.attrib.items():
        if key.split("}")[-1] == ACCESS_CMD or key.endswith(ACCESS_CMD):
            return value
    return None


def header_of(el) -> str:
    """Menu label with the mnemonic underscore removed; a bound header keeps its binding."""
    raw = el.get("Header") or ""
    if raw.startswith("{"):
        m = re.search(r"\{Binding\s+([A-Za-z0-9_.]+)", raw)
        return f"<bound:{m.group(1)}>" if m else "<bound>"
    return raw.replace("_", "")


def menu_path(stack: list[str]) -> str:
    return " > ".join(p for p in stack if p)


def declared_ids() -> dict[str, str]:
    """id value -> C# constant name, from PdfCommandIds."""
    out: dict[str, str] = {}
    for m in re.finditer(r'public const string (\w+)\s*=\s*"([^"]+)"', IDS.read_text()):
        out[m.group(2)] = m.group(1)
    return out


def walk(el, stack, rows):
    tag = strip_ns(el.tag)
    label = header_of(el) if tag == "MenuItem" else ""
    here = stack + ([label] if tag == "MenuItem" and label else stack[:0])

    if tag == "MenuItem":
        cmd = command_of(el)
        gesture = el.get("InputGesture")
        cid = command_id_of(el)
        # A submenu header with no command is structure, not an interaction.
        if cmd or gesture or cid:
            rows.append({
                "kind": "menu",
                "path": menu_path(here),
                "label": label,
                "command": cmd,
                "commandParameter": el.get("CommandParameter"),
                "shortcut": gesture,
                "commandId": cid,
            })
    elif tag == "Button":
        cmd = command_of(el)
        cid = command_id_of(el)
        if cmd or cid:
            rows.append({
                "kind": "button",
                "path": el.get("{http://schemas.microsoft.com/winfx/2006/xaml}Name") or el.get("Name") or "",
                "label": (el.get("ToolTip.Tip") or el.get("Content") or "").replace("_", ""),
                "command": cmd,
                "commandParameter": el.get("CommandParameter"),
                "shortcut": None,
                "commandId": cid,
            })

    for child in el:
        walk(child, here, rows)


def mouse_rows() -> list[dict]:
    """Pointer gestures the viewer handles, from the handler registrations."""
    rows = []
    for path in sorted((ROOT / "Excise.Avalonia/Controls").glob("PdfViewerControl*.cs")):
        text = path.read_text(errors="replace")
        for m in re.finditer(r"AddHandler\((\w+Event),\s*(\w+)", text):
            rows.append({
                "kind": "mouse",
                "path": f"{path.name}:{m.group(1)}",
                "label": m.group(1).replace("Event", ""),
                "command": m.group(2),
                "commandParameter": None,
                "shortcut": None,
                "commandId": None,
            })
    seen, out = set(), []
    for r in rows:
        key = (r["path"], r["command"])
        if key not in seen:
            seen.add(key)
            out.append(r)
    return out


def main() -> int:
    tree = ET.parse(XAML)
    rows: list[dict] = []
    walk(tree.getroot(), [], rows)
    rows.extend(mouse_rows())
    rows.sort(key=lambda r: (r["kind"], r["path"], r["label"] or "", r["command"] or ""))

    ids = declared_ids()
    ids_by_name = {name: value for value, name in ids.items()}
    used = {r["commandId"] for r in rows if r["commandId"]}

    # A command that only ever had a CLI home is not "unreachable from the GUI",
    # it is CLI-only by design (render.page, text.extract, automation.batch...).
    # PdfCommandRegistry declares those through its Cli(...) helper, so ask it
    # rather than guessing from the name.
    registry = (ROOT / "Excise.Core/Automation/PdfCommandRegistry.cs").read_text()
    # Two shapes declare a CLI home: the Cli(...) helper, and any other helper
    # carrying cliCommand: (Form(PdfCommandIds.FillForm, ..., cliCommand: "fill-form")).
    # Looking only for Cli(...) called fill-form and add-field GUI-unreachable when
    # they ship as CLI verbs.
    cli_only = set()
    chunks = registry.split("PdfCommandIds.")
    for chunk in chunks[1:]:
        name = re.match(r"(\w+)", chunk)
        if not name or name.group(1) not in ids_by_name:
            continue
        # the declaration ends where the next one begins
        if "cliCommand:" in chunk or chunk.lstrip().startswith(name.group(1)) and False:
            cli_only.add(ids_by_name[name.group(1)])
    for m in re.finditer(r"Cli\(PdfCommandIds\.(\w+)", registry):
        if m.group(1) in ids_by_name:
            cli_only.add(ids_by_name[m.group(1)])
    unreachable = sorted(v for v in ids if v not in used and v not in cli_only)
    cli_only_missing_gui = sorted(v for v in ids if v not in used and v in cli_only)
    unidentified = [
        {"kind": r["kind"], "path": r["path"], "label": r["label"], "command": r["command"]}
        for r in rows if not r["commandId"] and r["kind"] != "mouse"
    ]
    shortcuts = sorted(
        ({"shortcut": r["shortcut"], "path": r["path"], "commandId": r["commandId"]}
         for r in rows if r["shortcut"]),
        key=lambda s: s["shortcut"],
    )
    clashes = {}
    for s in shortcuts:
        clashes.setdefault(s["shortcut"], []).append(s["path"])
    duplicate_shortcuts = {k: v for k, v in clashes.items() if len(v) > 1}

    parameterised = {}
    for r in rows:
        if r["commandId"] and r.get("commandParameter"):
            parameterised.setdefault(r["commandId"], []).append(r["commandParameter"])
    parameterised = {k: sorted(set(v)) for k, v in sorted(parameterised.items())}

    doc = {
        "schemaVersion": 1,
        "issue": "#1374",
        "description": (
            "Every interaction a person can perform on the excise GUI: menu items, keyboard "
            "shortcuts, toolbar buttons and viewer mouse gestures, joined to the command id each "
            "invokes. Generated from Excise.App/Views/MainWindow.axaml and the viewer control; "
            "regenerate with scripts/check-gui-interaction-registry.sh."
        ),
        "whyThisExists": (
            "A command with no menu item, shortcut or button is unreachable, and a control with no "
            "command id cannot be driven by automation. Both have shipped — #1308's Sign Document "
            "was implemented, tested, and reachable from no production code. This is also the input "
            "to the AppleScript terminology (#1281) and the GUI workflow suite, so a control added "
            "to the XAML joins the scriptable surface and the test matrix automatically."
        ),
        "generatedBy": "scripts/build-gui-interaction-registry.py",
        "sourceRevision": subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True
        ).stdout.strip() or "unavailable",
        "summary": {
            "interactions": len(rows),
            "menuItems": sum(1 for r in rows if r["kind"] == "menu"),
            "buttons": sum(1 for r in rows if r["kind"] == "button"),
            "mouseGestures": sum(1 for r in rows if r["kind"] == "mouse"),
            "keyboardShortcuts": len(shortcuts),
            "declaredCommandIds": len(ids),
            "commandIdsReachableFromTheGui": len(used),
            "commandIdsWithNoGuiPath": len(unreachable),
            "cliOnlyCommandIds": len(cli_only_missing_gui),
            "controlsWithNoCommandId": len(unidentified),
            "duplicateShortcuts": len(duplicate_shortcuts),
            "parameterisedCommandIds": len(parameterised),
        },
        "interactions": rows,
        "keyboardShortcuts": shortcuts,
        "duplicateShortcuts": duplicate_shortcuts,
        "parameterisedCommandIds": parameterised,
        "commandIdsWithNoGuiPath": unreachable,
        "cliOnlyCommandIds": cli_only_missing_gui,
        "controlsWithNoCommandId": unidentified,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    s = doc["summary"]
    print(f"wrote {OUT.relative_to(ROOT)}: {s['interactions']} interactions "
          f"({s['menuItems']} menu, {s['buttons']} button, {s['mouseGestures']} mouse), "
          f"{s['keyboardShortcuts']} shortcuts, "
          f"{s['commandIdsWithNoGuiPath']} command ids with no GUI path "
          f"({s['cliOnlyCommandIds']} CLI-only by design), "
          f"{s['controlsWithNoCommandId']} controls with no command id")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
