#!/usr/bin/env bash
#
# Redaction leak assertions must not be excise refereeing excise (#1029).
#
# CLAUDE.md's central rule: "A tool must not be its own oracle for the property
# it exists to guarantee. excise confirming that excise removed the text proves
# only that its bugs are self-consistent." Three shipped leaks passed a green
# suite that way.
#
# So every redaction leak assertion must have a path to an assertion that does
# not depend on excise's own reading of the file:
#
#   * an independent extractor or renderer  (mutool, qpdf, ghostscript,
#     pdftocairo, pdftoppm, PDFBox, pdfium)
#   * a saved-bytes scan that decompresses  (SavedPdfLeakScanner, #1049)
#   * an ink differential                   (InkFraction over a region)
#
# A method asserting only on page.Text / ExtractAllText / Letters is testing
# the extractor against the remover — both of which are excise. The original
# file-level gate remains below as the cheap coarse check; #1077 adds the
# method-level gate because one mutool call elsewhere in the file must not
# bless a different, self-oracle-only leak assertion.
#
# ── Why a DETECTOR rather than a review ─────────────────────────────────────
#
# #1029 was scoped as "audit 48 files and write a reason for each". A review
# does not converge and cannot be re-run. This is the same question asked
# mechanically: it produces a list, it takes a second, and it can gate.
#
# It has already earned that: a hand pass over #1049 MISSED
# LineContinuationRedactionLeakTests.cs — a file with "LeakTests" in its name —
# and a six-line detector found it immediately.
#
# Usage: scripts/check-redaction-oracles.sh [--update]
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"
ALLOW="tests/redaction-self-oracle-allowlist.txt"
METHOD_ALLOW="tests/redaction-self-oracle-method-allowlist.txt"
UPDATE="${1:-}"

INDEPENDENT='Mutool|Qpdf|Ghostscript|Pdftocairo|Pdftoppm|PdfBox|PdfiumNative|SavedPdfLeakScanner|InkFraction|ReferenceRedactor|VeraPdf'
SELF='\.Text\.Should|ExtractAllText|\.Letters|GetLetters'

offenders=""
method_offenders=""
# #1122: the pattern used to be "*Redaction*Tests.cs" ONLY, which meant
# HiddenTextDetectorTests.cs -- the tests for the detector whose entire job is
# finding bad redactions -- was invisible to this gate. Not allow-listed,
# not failing: unseen. The rule this script enforces is that a tool must not
# be its own oracle for the property it exists to guarantee, and the detector
# for that property was exempt by filename.
for f in $(find Excise.*.Tests \
                \( -name "*Redaction*Tests.cs" -o -name "*HiddenText*Tests.cs" -o -name "*Audit*Tests.cs" \) \
                -not -path '*/obj/*' -not -path '*/bin/*' | sort); do
  # Only files that actually assert about leaks are in scope; a pure geometry
  # or workflow test has nothing for an oracle to corroborate.
  grep -qE "$SELF" "$f" || continue
  grep -qE "$INDEPENDENT" "$f" && continue
  offenders="${offenders}${f}"$'\n'
done
offenders=$(printf '%s' "$offenders" | grep . || true)

# #1077: classify individual [Fact]/[Theory] methods. This is deliberately a
# small lexical detector, not a C# parser: it is fast enough to run as a gate,
# and catches the real blind spot where one file has both a mutool-backed test
# and a separate page.Text-only leak assertion. Helpers/call graphs remain a
# documented future Roslyn upgrade; keep helper-backed methods explicitly
# allow-listed until that exists rather than pretending a regex proved them.
while IFS= read -r f; do
  [[ -n "$f" ]] || continue
  method_offenders+="$(awk -v self="$SELF" -v independent="$INDEPENDENT" '
    function flush() {
      if (!in_test || !has_self || has_independent) return
      if (method == "") method = "<unresolved-method>"
      print FILENAME "::" method
    }
    /^[[:space:]]*\[(Fact|Theory)(\(|\])/ {
      flush()
      in_test = 1
      has_self = 0
      has_independent = 0
      method = ""
      looking_for_method = 1
    }
    {
      if (!in_test) next
      if ($0 ~ self) has_self = 1
      if ($0 ~ independent) has_independent = 1
      if (looking_for_method && $0 ~ /^[[:space:]]*(public|protected|internal|private)[[:space:]].*\(/) {
        signature = $0
        sub(/[[:space:]]*\(.*/, "", signature)
        count = split(signature, words, /[[:space:]]+/)
        method = words[count]
        looking_for_method = 0
      }
    }
    END { flush() }
  ' "$f")"$'\n'
done < <(find Excise.*.Tests \
              \( -name "*Redaction*Tests.cs" -o -name "*HiddenText*Tests.cs" -o -name "*Audit*Tests.cs" \) \
              -not -path '*/obj/*' -not -path '*/bin/*' | sort)
method_offenders=$(printf '%s' "$method_offenders" | grep . || true)

if [[ "$UPDATE" == "--update" ]]; then
  {
    echo "# Redaction test files whose leak assertions rely on excise's own reading."
    echo "# Generated by scripts/check-redaction-oracles.sh --update; reasons are hand-written."
    echo "# Removing a line is how corroboration is claimed back. Each entry is a file"
    echo "# where a leak could pass unnoticed if the extractor and the remover share a bug."
    while IFS= read -r f; do
      [[ -n "$f" ]] || continue
      reason=$( { grep -F "$f" "$ALLOW" 2>/dev/null || true; } | sed 's/^[^#]*#//' | head -1 )
      printf '%s  #%s\n' "$f" "${reason:- no independent oracle yet}"
    done <<< "$offenders"
  } > "$ALLOW.new"
  mv "$ALLOW.new" "$ALLOW"
  {
    echo "# Redaction test methods whose leak assertions rely on excise's own reading."
    echo "# Generated by scripts/check-redaction-oracles.sh --update; reasons are hand-written."
    echo "# Format: path/to/Test.cs::MethodName  # reason"
    while IFS= read -r entry; do
      [[ -n "$entry" ]] || continue
      reason=$( { grep -F "$entry" "$METHOD_ALLOW" 2>/dev/null || true; } | sed 's/^[^#]*#//' | head -1 )
      if [[ -z "$reason" ]]; then
        file="${entry%%::*}"
        reason=$( { grep -F "$file" "$ALLOW" 2>/dev/null || true; } | sed 's/^[^#]*#//' | head -1 )
      fi
      printf '%s  #%s\n' "$entry" "${reason:- no independent oracle yet}"
    done <<< "$method_offenders"
  } > "$METHOD_ALLOW.new"
  mv "$METHOD_ALLOW.new" "$METHOD_ALLOW"
  echo "wrote $ALLOW and $METHOD_ALLOW"
  exit 0
fi

[[ -f "$ALLOW" ]] || { echo "❌ no allowlist at $ALLOW — create it with --update" >&2; exit 1; }
[[ -f "$METHOD_ALLOW" ]] || { echo "❌ no method allowlist at $METHOD_ALLOW — create it with --update" >&2; exit 1; }

declared=$(grep -v '^#' "$ALLOW" | awk '{print $1}' | grep . | sort -u || true)
current=$(printf '%s' "$offenders" | sort -u)
declared_methods=$(grep -v '^#' "$METHOD_ALLOW" | awk '{print $1}' | grep . | sort -u || true)
current_methods=$(printf '%s' "$method_offenders" | sort -u)

new=$(comm -23 <(printf '%s\n' $current) <(printf '%s\n' $declared) | grep . || true)
fixed=$(comm -13 <(printf '%s\n' $current) <(printf '%s\n' $declared) | grep . || true)
new_methods=$(comm -23 <(printf '%s\n' "$current_methods") <(printf '%s\n' "$declared_methods") | grep . || true)
fixed_methods=$(comm -13 <(printf '%s\n' "$current_methods") <(printf '%s\n' "$declared_methods") | grep . || true)

status=0
if [[ -n "$new" ]]; then
  echo "❌ redaction test file(s) with NO independent oracle and no declared reason:" >&2
  printf '%s\n' "$new" | sed 's/^/     /' >&2
  echo "   Add a mutool/qpdf/ink-differential or SavedPdfLeakScanner assertion," >&2
  echo "   or declare it: scripts/check-redaction-oracles.sh --update" >&2
  status=1
fi
if [[ -n "$fixed" ]]; then
  echo "❌ file(s) listed as self-oracle-only now HAVE an independent oracle:" >&2
  printf '%s\n' "$fixed" | sed 's/^/     /' >&2
  echo "   Remove them from $ALLOW — corroboration coming back must be recorded," >&2
  echo "   or the list becomes a blanket excuse." >&2
  status=1
fi
if [[ -n "$new_methods" ]]; then
  echo "❌ redaction test method(s) with NO independent oracle and no declared reason:" >&2
  printf '%s\n' "$new_methods" | sed 's/^/     /' >&2
  echo "   Add a non-excise oracle in that method, or declare it with a reason:" >&2
  echo "   scripts/check-redaction-oracles.sh --update" >&2
  status=1
fi
if [[ -n "$fixed_methods" ]]; then
  echo "❌ method(s) listed as self-oracle-only now HAVE an independent oracle:" >&2
  printf '%s\n' "$fixed_methods" | sed 's/^/     /' >&2
  echo "   Remove them from $METHOD_ALLOW — corroboration coming back must be recorded." >&2
  status=1
fi

if (( status == 0 )); then
  declared_file_count=$(printf '%s\n' "$declared" | awk 'NF { count++ } END { print count + 0 }')
  declared_method_count=$(printf '%s\n' "$declared_methods" | awk 'NF { count++ } END { print count + 0 }')
  echo "✅ every redaction test file and leak-asserting method is either corroborated"
  echo "   by a non-excise oracle or a declared, reasoned exception"
  echo "   (${declared_file_count} files; ${declared_method_count} methods)."
fi
exit $status
