#!/usr/bin/env bash
#
# Redaction leak assertions must not be excise refereeing excise (#1029).
#
# CLAUDE.md's central rule: "A tool must not be its own oracle for the property
# it exists to guarantee. excise confirming that excise removed the text proves
# only that its bugs are self-consistent." Three shipped leaks passed a green
# suite that way.
#
# So a redaction test file must contain at least ONE assertion that does not
# depend on excise's own reading of the file:
#
#   * an independent extractor or renderer  (mutool, qpdf, ghostscript,
#     pdftocairo, pdftoppm, PDFBox, pdfium)
#   * a saved-bytes scan that decompresses  (SavedPdfLeakScanner, #1049)
#   * an ink differential                   (InkFraction over a region)
#
# A file with none of those, asserting only on page.Text / ExtractAllText /
# Letters, is testing the extractor against the remover — both of which are
# excise.
#
# ── Why a DETECTOR rather than a review ─────────────────────────────────────
#
# #1029 was scoped as "audit 48 files and write a reason for each". A review
# does not converge and cannot be re-run. This is the same question asked
# mechanically: it produces a list, it takes a second, and it can gate.
#
# It has already earned that: a hand pass over #1049 MISSED
# LineContinuationRedactionLeakTests.cs — a file with "LeakTests" in its name —
# and a six-line detector found it immediately.
#
# Usage: scripts/check-redaction-oracles.sh [--update]
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"
ALLOW="tests/redaction-self-oracle-allowlist.txt"
UPDATE="${1:-}"

INDEPENDENT='Mutool|Qpdf|Ghostscript|Pdftocairo|Pdftoppm|PdfBox|PdfiumNative|SavedPdfLeakScanner|InkFraction|ReferenceRedactor|VeraPdf'
SELF='\.Text\.Should|ExtractAllText|\.Letters|GetLetters'

offenders=""
for f in $(find Excise.*.Tests -name "*Redaction*Tests.cs" -not -path '*/obj/*' -not -path '*/bin/*' | sort); do
  # Only files that actually assert about leaks are in scope; a pure geometry
  # or workflow test has nothing for an oracle to corroborate.
  grep -qE "$SELF" "$f" || continue
  grep -qE "$INDEPENDENT" "$f" && continue
  offenders="${offenders}${f}"$'\n'
done
offenders=$(printf '%s' "$offenders" | grep . || true)

if [[ "$UPDATE" == "--update" ]]; then
  {
    echo "# Redaction test files whose leak assertions rely on excise's own reading."
    echo "# Generated by scripts/check-redaction-oracles.sh --update; reasons are hand-written."
    echo "# Removing a line is how corroboration is claimed back. Each entry is a file"
    echo "# where a leak could pass unnoticed if the extractor and the remover share a bug."
    while IFS= read -r f; do
      [[ -n "$f" ]] || continue
      reason=$( { grep -F "$f" "$ALLOW" 2>/dev/null || true; } | sed 's/^[^#]*#//' | head -1 )
      printf '%s  #%s\n' "$f" "${reason:- no independent oracle yet}"
    done <<< "$offenders"
  } > "$ALLOW.new"
  mv "$ALLOW.new" "$ALLOW"
  echo "wrote $ALLOW"
  exit 0
fi

[[ -f "$ALLOW" ]] || { echo "❌ no allowlist at $ALLOW — create it with --update" >&2; exit 1; }

declared=$(grep -v '^#' "$ALLOW" | awk '{print $1}' | grep . | sort -u)
current=$(printf '%s' "$offenders" | sort -u)

new=$(comm -23 <(printf '%s\n' $current) <(printf '%s\n' $declared) | grep . || true)
fixed=$(comm -13 <(printf '%s\n' $current) <(printf '%s\n' $declared) | grep . || true)

status=0
if [[ -n "$new" ]]; then
  echo "❌ redaction test file(s) with NO independent oracle and no declared reason:" >&2
  printf '%s\n' "$new" | sed 's/^/     /' >&2
  echo "   Add a mutool/qpdf/ink-differential or SavedPdfLeakScanner assertion," >&2
  echo "   or declare it: scripts/check-redaction-oracles.sh --update" >&2
  status=1
fi
if [[ -n "$fixed" ]]; then
  echo "❌ file(s) listed as self-oracle-only now HAVE an independent oracle:" >&2
  printf '%s\n' "$fixed" | sed 's/^/     /' >&2
  echo "   Remove them from $ALLOW — corroboration coming back must be recorded," >&2
  echo "   or the list becomes a blanket excuse." >&2
  status=1
fi

if (( status == 0 )); then
  echo "✅ every redaction test file is either corroborated by a non-excise oracle"
  echo "   or a declared, reasoned exception ($(printf '%s' "$declared" | grep -c . || echo 0) declared)."
fi
exit $status
