using System;
using System.Collections.Generic;
using Excise.Core.Document;

namespace Excise.Core.Redaction.Recovery;

/// <summary>
/// #1592 — the "tool-specific leftovers" class: material a redactor forgot to
/// regenerate or remove, which survives alongside a page that was correctly
/// rewritten.
///
/// <para>These share a shape that makes them worth one class. None is text the
/// channel can read, each is a container whose CONTENTS predate the redaction,
/// and each is invisible to every check that looks at page content — including
/// this project's own primary assertion, which reads the content stream.</para>
///
/// <list type="bullet">
///   <item><b>Page thumbnails</b> (<c>/Thumb</c>, §12.3.4). A pre-rendered
///   picture of the page, stored per page, which a viewer may show in its
///   sidebar. A redactor that rewrites page content and leaves <c>/Thumb</c>
///   alone ships a picture of the UNREDACTED page. Nothing in the text layer
///   reveals it and no text-based audit can see it.</item>
///   <item><b>Embedded files</b> (<c>/EmbeddedFiles</c>, <c>/AF</c>). The
///   attachment is a whole separate document carried inside this one; redacting
///   the host page does nothing to it. excise scrubs these by default in the
///   GUI redacted-copy flow (#467), so this channel is mostly about other
///   people's output — but it also catches a excise path where the scrub was
///   not requested.</item>
/// </list>
///
/// <para><b>Confidence is <see cref="RecoveryConfidence.PresentOnly"/>, and
/// that is not a hedge.</b> The channel establishes that a container survives
/// and says which one; it does not decode a thumbnail into text or open an
/// attachment. Both are real leaks and neither is a recovered VALUE. Turning
/// the thumbnail back into a visible image is <c>--restore</c>'s job
/// (#1588).</para>
/// </summary>
public static class ResidualArtefactRecovery
{
    /// <param name="Kind">"thumbnail" or "attachment".</param>
    /// <param name="PageNumber">1-based for a thumbnail; 0 for a document-level attachment.</param>
    /// <param name="Description">Human-readable, including a size where known.</param>
    public readonly record struct ResidualArtefact(string Kind, int PageNumber, string Description);

    public static IReadOnlyList<ResidualArtefact> Scan(PdfDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);
        var found = new List<ResidualArtefact>();
        ScanThumbnails(document, found);
        ScanAttachments(document, found);
        return found;
    }

    private static void ScanThumbnails(PdfDocument document, List<ResidualArtefact> found)
    {
        for (var p = 1; p <= document.PageCount; p++)
        {
            try
            {
                if (document.GetPage(p).ThumbnailStream is not { } thumb) continue;
                var width = thumb.GetOptional("Width");
                var height = thumb.GetOptional("Height");
                var size = width is Primitives.PdfInteger w && height is Primitives.PdfInteger h
                    ? $" ({w.Value}x{h.Value})"
                    : "";
                found.Add(new ResidualArtefact(
                    "thumbnail", p,
                    $"page thumbnail /Thumb{size} — a pre-rendered picture of the page, " +
                    "not regenerated by the redaction"));
            }
            catch { /* a page whose /Thumb will not resolve reports nothing */ }
        }
    }

    private static void ScanAttachments(PdfDocument document, List<ResidualArtefact> found)
    {
        // #1667: the SHARED enumeration. This used to call GetEmbeddedFiles(),
        // which is catalog-only, while the carrier channel walked page and
        // annotation /AF too — so a file hung off a page was reported by one
        // channel and not the other, and the attachment channel is the one
        // carrying the description a reader needs.
        IReadOnlyList<EmbeddedFileEnumerator.Found> files;
        try { files = EmbeddedFileEnumerator.All(document); }
        catch { return; }

        foreach (var (file, page, source) in files)
        {
            // /UF or /F is what a user sees; the name-tree key is the fallback.
            var name = !string.IsNullOrWhiteSpace(file.FileName) ? file.FileName!
                : !string.IsNullOrWhiteSpace(file.Name) ? file.Name
                : "(unnamed)";
            found.Add(new ResidualArtefact(
                "attachment", page,
                $"embedded file \"{name}\" ({source}) — a whole document carried inside this " +
                "one, untouched by a page redaction"));
        }
    }
}
