using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

// Candidate evidence never authorizes deletion or refactoring. See issue #1941.
if (args.Length == 0 || args[0] is not ("capture" or "self-test"))
    throw new ArgumentException("Usage: capture ROOT OUTPUT [YYYY-MM-DD] | self-test ROOT");
var repository = Path.GetFullPath(args.Length > 1 ? args[1] : ".");
if (args[0] == "self-test") { SelfTest(repository); return; }
// A review date is explicit input: default captures do not vary with today's date.
var reviewDate = args.Length > 3 ? DateOnly.ParseExact(args[3], "yyyy-MM-dd", CultureInfo.InvariantCulture) : (DateOnly?)null;
File.WriteAllText(args[2], Serialize(Build(repository, reviewDate)), new UTF8Encoding(false));

static string Hash(string text) => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(text)));
static string Normalize(string text) => text.Replace("\r\n", "\n").Replace('\r', '\n');
static bool HasGeneratedHeader(string source)
{
    // Only leading comment trivia is a header; code/literals and directives
    // terminate the header region. See #1939.
    var trivia = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.CSharp14)).GetRoot().GetFirstToken(includeZeroWidth: true).LeadingTrivia;
    foreach (var item in trivia)
    {
        if (item.IsKind(SyntaxKind.WhitespaceTrivia) || item.IsKind(SyntaxKind.EndOfLineTrivia)) continue;
        if (item.Kind() is not (SyntaxKind.SingleLineCommentTrivia or SyntaxKind.MultiLineCommentTrivia
            or SyntaxKind.SingleLineDocumentationCommentTrivia or SyntaxKind.MultiLineDocumentationCommentTrivia)) return false;
        if (item.ToFullString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) return true;
    }
    return false;
}
static string Serialize(object value) => JsonSerializer.Serialize(value, new JsonSerializerOptions { WriteIndented = true }) + "\n";
static string Git(string root, params string[] arguments)
{
    var start = new ProcessStartInfo("git") { WorkingDirectory = root, RedirectStandardOutput = true, RedirectStandardError = true };
    foreach (var argument in arguments) start.ArgumentList.Add(argument);
    using var process = Process.Start(start)!;
    var output = process.StandardOutput.ReadToEnd(); var error = process.StandardError.ReadToEnd(); process.WaitForExit();
    if (process.ExitCode != 0) throw new InvalidOperationException(error);
    return output;
}
static Report Build(string root, DateOnly? reviewDate)
{
    var tracked = Git(root, "ls-files", "-z").Split('\0', StringSplitOptions.RemoveEmptyEntries).Order(StringComparer.Ordinal).ToArray();
    var projects = tracked.Where(p => p.EndsWith(".csproj", StringComparison.Ordinal)).ToArray();
    var scopeText = Normalize(File.ReadAllText(Path.Combine(root, "architecture/repository-scope.json")));
    using var scope = JsonDocument.Parse(scopeText);
    var inputs = new List<Input>(); var exclusions = new List<Exclusion>(); var sources = new Dictionary<string, string>();
    foreach (var path in tracked.Where(p => p.EndsWith(".cs", StringComparison.Ordinal)))
    {
        if (!File.Exists(Path.Combine(root, path))) throw new InvalidOperationException($"Tracked input missing: {path}");
        var source = Normalize(File.ReadAllText(Path.Combine(root, path)));
        var project = projects.Where(p => path.StartsWith(p[..(p.LastIndexOf('/') + 1)], StringComparison.Ordinal))
            .OrderByDescending(p => p.LastIndexOf('/')).ThenBy(p => p, StringComparer.Ordinal).FirstOrDefault();
        var classification = scope.RootElement.GetProperty("defaultProjectClassification").GetString()!;
        string? reason = null;
        foreach (var group in new[] { "excludedRoots", "reviewOnlyRoots" })
        foreach (var rule in scope.RootElement.GetProperty(group).EnumerateArray())
        {
            var prefix = rule.GetProperty("path").GetString()!;
            if (path == prefix || path.StartsWith(prefix + "/", StringComparison.Ordinal) || (prefix is "bin" or "obj" && path.Split('/').Contains(prefix)))
            { classification = rule.GetProperty("classification").GetString()!; reason = rule.GetProperty("reason").GetString(); }
        }
        if (reason is null && project is null) { classification = "unowned"; reason = "No tracked ancestor project."; }
        if (reason is null)
        {
            foreach (var rule in scope.RootElement.GetProperty("projectRules").EnumerateArray())
                if (Regex.IsMatch(project!, "^" + Regex.Escape(rule.GetProperty("pattern").GetString()!).Replace("\\*", ".*") + "$", RegexOptions.CultureInvariant))
                { classification = rule.GetProperty("classification").GetString()!; break; }
            if (path.EndsWith(".g.cs", StringComparison.Ordinal) || path.EndsWith(".generated.cs", StringComparison.Ordinal) || HasGeneratedHeader(source))
            { classification = "generated"; reason = "Generated filename or auto-generated header."; }
        }
        inputs.Add(new(path, project, classification, Hash(source)));
        if (reason is not null) exclusions.Add(new(path, classification, reason));
        else sources.Add(path, source);
    }
    var occurrences = new List<Occurrence>(); var invocations = new List<Caller>();
    foreach (var group in inputs.Where(i => sources.ContainsKey(i.Path)).GroupBy(i => i.Project).OrderBy(g => g.Key, StringComparer.Ordinal))
    {
        var trees = group.Select(i => CSharpSyntaxTree.ParseText(sources[i.Path], new CSharpParseOptions(LanguageVersion.CSharp14), i.Path)).ToArray();
        var compilation = CSharpCompilation.Create("DuplicateEvidence", trees);
        foreach (var tree in trees)
        {
            if (tree.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error)) throw new InvalidOperationException($"Syntax errors in {tree.FilePath}; refusing partial evidence.");
            var input = group.Single(i => i.Path == tree.FilePath); var model = compilation.GetSemanticModel(tree);
            foreach (var method in tree.GetRoot().DescendantNodes().OfType<BaseMethodDeclarationSyntax>())
            {
                var symbol = model.GetDeclaredSymbol(method); var body = Body(method);
                if (symbol is null || body is null) continue;
                var key = input.Project + "::" + symbol.GetDocumentationCommentId();
                var methodLine = method.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
                AddOccurrence(occurrences, body, model, input, key, symbol.Name, methodLine, "method", 0);
                var ordinal = 0;
                foreach (var block in body.DescendantNodes().OfType<BlockSyntax>())
                    AddOccurrence(occurrences, block, model, input, key, symbol.Name, methodLine, "block", ++ordinal);
                foreach (var call in body.DescendantNodesAndSelf().OfType<InvocationExpressionSyntax>())
                {
                    var name = call.Expression switch { MemberAccessExpressionSyntax m => m.Name.Identifier.ValueText, SimpleNameSyntax n => n.Identifier.ValueText, _ => "" };
                    if (name.Length > 0) invocations.Add(new(key, tree.FilePath, call.GetLocation().GetLineSpan().StartLinePosition.Line + 1, name));
                }
            }
        }
    }
    var registryPath = Path.Combine(root, "tests/code-health/intentional-duplicates.json");
    var registryText = Normalize(File.ReadAllText(registryPath));
    var registry = JsonSerializer.Deserialize<Registry>(registryText)!;
    Validate(registry);
    var topologyPath = Path.Combine(root, "architecture/generated/code-topology.json");
    var topologyText = File.Exists(topologyPath) ? File.ReadAllText(topologyPath) : null;
    using var topology = topologyText is null ? null : JsonDocument.Parse(topologyText);
    var topologyRevision = topology?.RootElement.GetProperty("sourceRevision").GetString();
    var topologyRows = topology?.RootElement.GetProperty("symbols").EnumerateArray().Where(s => s.GetProperty("kind").GetString() == "method").ToArray() ?? [];
    // A Git diff proves staleness, but absence of a diff does not prove generator freshness.
    var topologyStatus = "missing";
    if (topologyRevision is not null)
    {
        try { topologyStatus = Git(root, "diff", "--name-only", topologyRevision, "--", "*.cs", "*.csproj", "architecture/design.json").Length == 0 ? "revision-inputs-match; generator freshness unverified" : "stale-source-inputs; refresh before refactoring"; }
        catch (InvalidOperationException) { topologyStatus = "source-revision-unavailable; refresh before refactoring"; }
    }
    var candidates = occurrences.GroupBy(o => o.Kind + ":" + o.NormalizedHash).Where(g => g.Count() > 1)
        .OrderBy(g => g.Key, StringComparer.Ordinal).Select(g =>
        {
            var first = g.First(); var id = "clone-" + Hash(g.Key);
            var entry = registry.Entries.SingleOrDefault(e => e.CandidateId == id);
            var status = entry is null ? "review-candidate" : reviewDate is null ? "registered; review date not evaluated" : DateOnly.ParseExact(entry.ReviewBy, "yyyy-MM-dd", CultureInfo.InvariantCulture) < reviewDate ? "expired-registration; review-required" : "registered-intentional";
            var evidence = g.OrderBy(o => o.SymbolKey, StringComparer.Ordinal).ThenBy(o => o.Path, StringComparer.Ordinal).ThenBy(o => o.StartLine).Select(o =>
            {
                var rows = topologyRows.Where(s => s.GetProperty("file").GetString() == o.Path && s.GetProperty("startLine").GetInt32() == o.MethodStartLine
                    && s.GetProperty("symbol").GetString() == o.Symbol).ToArray();
                var join = rows.Length == 1 ? rows[0].Clone() : (JsonElement?)null;
                return new Evidence(o, invocations.Where(c => c.TargetName == o.MethodName).Distinct().OrderBy(c => c.Path, StringComparer.Ordinal).ThenBy(c => c.Line).ThenBy(c => c.OwnerSymbolKey, StringComparer.Ordinal).ToArray(), join,
                    rows.Length == 1 ? "unique path+declaration-line+symbol join; consult topology provenance" : rows.Length == 0 ? "no topology match; reachability unknown" : "ambiguous topology match; reachability unknown");
            }).ToArray();
            return new Candidate(id, first.Kind, g.Select(o => o.ExactHash).Distinct().Count() == 1 ? "exact-tokens" : "parameter-local-alpha-renaming", first.NormalizedHash, first.Tokens,
                status, entry, evidence);
        }).ToArray();
    return new(1, "Excise.DuplicateEvidence/1", Hash(Normalize(File.ReadAllText(Path.Combine(root, "tools/Excise.DuplicateEvidence/Program.cs")))),
        typeof(CSharpCompilation).Assembly.GetName().Version!.ToString(), Hash(scopeText), Hash(registryText), reviewDate?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
        "CSharp14; syntax compilation without references/MSBuild/preprocessor symbols. Bound parameters retain ordinal identity; locals are alpha-renamed by first token occurrence. All other identifier names, token kinds, operators and literal spelling remain significant. Trivia ignored. Minimum 60 tokens and 3 non-block statements. Whole method bodies and complete nested blocks only; root method blocks are not counted twice. No approximate/fuzzy or arbitrary fragment matching; properties/accessors/local functions/lambdas are not separate owners.",
        "Tracked *.cs under nearest tracked *.csproj; LF SHA-256; repository-scope exclusions, generated files/headers and unowned files excluded explicitly; untracked files ignored. Classifications retained; tests and shipping candidates require separate review.",
        "Name-only invocation candidates are conservative caller leads, not bound call edges. Topology provides semantic fanIn, reachability, seeds, workflows and test-project evidence where a unique source-span join exists. Stale/unverified topology cannot prove safety; independent reachability checks are required before refactoring. No composite score, gate, deletion or behavior change.",
        "dotnet run --project tools/Excise.DuplicateEvidence -- capture . OUT.json [YYYY-MM-DD]",
        new(topologyText is null ? null : Hash(topologyText), topologyRevision, topologyStatus, "architecture/generated/code-topology.json; scripts/check-reachability.sh --topology-output OUT.json"),
        inputs.ToArray(), exclusions.ToArray(), registry.Entries.Where(e => !candidates.Any(c => c.Id == e.CandidateId)).Select(e => e.CandidateId).Order(StringComparer.Ordinal).ToArray(), candidates);
}
static SyntaxNode? Body(BaseMethodDeclarationSyntax method) => method switch
{
    MethodDeclarationSyntax m => (SyntaxNode?)m.Body ?? m.ExpressionBody?.Expression,
    ConstructorDeclarationSyntax c => (SyntaxNode?)c.Body ?? c.ExpressionBody?.Expression,
    DestructorDeclarationSyntax d => (SyntaxNode?)d.Body ?? d.ExpressionBody?.Expression,
    OperatorDeclarationSyntax o => (SyntaxNode?)o.Body ?? o.ExpressionBody?.Expression,
    ConversionOperatorDeclarationSyntax c => (SyntaxNode?)c.Body ?? c.ExpressionBody?.Expression,
    _ => null
};
static void AddOccurrence(List<Occurrence> rows, SyntaxNode body, SemanticModel model, Input input, string key, string name, int methodLine, string kind, int ordinal)
{
    var tokens = body.DescendantTokens().ToArray();
    if (tokens.Length < 60 || body.DescendantNodesAndSelf().Count(n => n is StatementSyntax and not BlockSyntax and not EmptyStatementSyntax) < 3) return;
    var owner = body.Ancestors().OfType<BaseMethodDeclarationSyntax>().First();
    var ownerSymbol = model.GetDeclaredSymbol(owner)!;
    var parameterScopes = new Dictionary<ISymbol, int>(SymbolEqualityComparer.Default) { [ownerSymbol] = 0 };
    var bindings = new Dictionary<ISymbol, int>(SymbolEqualityComparer.Default);
    var normalized = new List<string>(); var exact = new List<string>();
    foreach (var token in tokens)
    {
        var value = token.Text;
        exact.Add(token.RawKind + ":" + value);
        if (token.IsKind(SyntaxKind.IdentifierToken))
        {
            var symbol = token.Parent switch
            {
                IdentifierNameSyntax n => model.GetSymbolInfo(n).Symbol,
                VariableDeclaratorSyntax n => model.GetDeclaredSymbol(n),
                ParameterSyntax n => model.GetDeclaredSymbol(n),
                ForEachStatementSyntax n when n.Identifier == token => model.GetDeclaredSymbol(n),
                SingleVariableDesignationSyntax n => model.GetDeclaredSymbol(n),
                CatchDeclarationSyntax n when n.Identifier == token => model.GetDeclaredSymbol(n),
                _ => null
            };
            if (symbol is IParameterSymbol parameter)
            {
                if (!parameterScopes.TryGetValue(parameter.ContainingSymbol, out var scopeIndex))
                { scopeIndex = parameterScopes.Count; parameterScopes.Add(parameter.ContainingSymbol, scopeIndex); }
                value = "$parameter" + scopeIndex + "." + parameter.Ordinal;
            }
            else if (symbol is ILocalSymbol)
            {
                if (!bindings.TryGetValue(symbol, out var index)) { index = bindings.Count; bindings.Add(symbol, index); }
                value = "$binding" + index;
            }
        }
        normalized.Add(token.RawKind + ":" + value);
    }
    var span = body.GetLocation().GetLineSpan();
    var displayFormat = new SymbolDisplayFormat(typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        memberOptions: SymbolDisplayMemberOptions.IncludeContainingType | SymbolDisplayMemberOptions.IncludeParameters | SymbolDisplayMemberOptions.IncludeType,
        parameterOptions: SymbolDisplayParameterOptions.IncludeType | SymbolDisplayParameterOptions.IncludeName,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);
    rows.Add(new(key + "@" + input.Path + "::" + kind + ":" + ordinal, key, ownerSymbol.ToDisplayString(displayFormat), name, input.Project!, input.Classification, input.Path, methodLine,
        span.StartLinePosition.Line + 1, span.StartLinePosition.Character + 1, span.EndLinePosition.Line + 1, span.EndLinePosition.Character + 1,
        kind, Hash(Serialize(exact)), Hash(Serialize(normalized)), normalized.ToArray()));
}
static void Validate(Registry registry)
{
    if (registry.SchemaVersion != 1) throw new InvalidOperationException("Unsupported intentional-duplicate registry schema.");
    if (registry.Entries.Select(e => e.CandidateId).Distinct().Count() != registry.Entries.Length) throw new InvalidOperationException("Duplicate registry candidate IDs.");
    foreach (var entry in registry.Entries)
        if (!Regex.IsMatch(entry.CandidateId, "^clone-[a-f0-9]{64}$", RegexOptions.CultureInvariant) || !Regex.IsMatch(entry.Issue, "^https://github.com/marctjones/excise/issues/[1-9][0-9]*$", RegexOptions.CultureInvariant)
            || string.IsNullOrWhiteSpace(entry.Rationale) || !DateOnly.TryParseExact(entry.ReviewBy, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out _))
            throw new InvalidOperationException("Every registry entry requires a candidate ID, Excise issue URL, rationale and ISO review date.");
}
static void SelfTest(string repository)
{
    foreach (var sample in new[] { "class Marker { string Text = \"<auto-generated/>\"; }", "class Marker {} // <auto-generated/>", "#nullable enable\n// <auto-generated/>\nclass Marker {}" })
        if (HasGeneratedHeader(sample)) throw new Exception("Non-header generated marker excluded source.");
    foreach (var sample in new[] { " \n// license\n// <auto-generated/>\nclass Marker {}", "/* <AUTO-GENERATED> */\nclass Marker {}" })
        if (!HasGeneratedHeader(sample)) throw new Exception("Leading generated comment header missed.");
    const string source = "class Fixture { int A(int input) { int result = 0; for (int i=0;i<input;i++) { result += i * 3; if (result > 100) result -= 4; } result += input; result *= 2; result -= 1; result = System.Math.Abs(result + input); return result; } int B(int value) { int total = 0; for (int j=0;j<value;j++) { total += j * 3; if (total > 100) total -= 4; } total += value; total *= 2; total -= 1; total = System.Math.Abs(total + value); return total; } int C(int input) { int result = 0; for (int i=0;i<input;i++) { result += i * 7; if (result > 100) result -= 4; } result += input; result *= 2; result -= 1; result = System.Math.Abs(result + input); return result; } int Tiny() => 1; int Use() => A(10); }";
    var tree = CSharpSyntaxTree.ParseText(source); var model = CSharpCompilation.Create("Fixture", [tree]).GetSemanticModel(tree);
    var rows = new List<Occurrence>();
    foreach (var method in tree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>())
        AddOccurrence(rows, Body(method)!, model, new("Fixture.cs", "Fixture.csproj", "shipping", Hash(source)), method.Identifier.Text, method.Identifier.Text, 1, "method", 0);
    if (rows.Count != 3 || rows[0].NormalizedHash != rows[1].NormalizedHash || rows[0].ExactHash == rows[1].ExactHash || rows[0].NormalizedHash == rows[2].NormalizedHash)
        throw new Exception($"Planted local rename, changed literal or tiny-wrapper precision boundary failed; retained {rows.Count} methods.");
    foreach (var mutated in new[] { source.Replace("+= i * 3", "-= i * 3", StringComparison.Ordinal), source.Replace("Math.Abs", "Math.Sign", StringComparison.Ordinal) })
    {
        var changedTree = CSharpSyntaxTree.ParseText(mutated); var changedModel = CSharpCompilation.Create("Changed", [changedTree]).GetSemanticModel(changedTree);
        var changed = new List<Occurrence>(); var node = changedTree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().First();
        AddOccurrence(changed, Body(node)!, changedModel, new("Fixture.cs", "Fixture.csproj", "shipping", Hash(mutated)), "A", "A", 1, "method", 0);
        if (rows[0].NormalizedHash == changed.Single().NormalizedHash) throw new Exception("Operator/callee changes were erased.");
    }
    var parameterHashes = new List<string>();
    foreach (var variant in new[] { source.Replace("A(int input)", "A(int input, int other)", StringComparison.Ordinal),
        source.Replace("A(int input)", "A(int input, int other)", StringComparison.Ordinal).Replace("Abs(result + input)", "Abs(result + other)", StringComparison.Ordinal) })
    {
        var variantTree = CSharpSyntaxTree.ParseText(variant); var variantModel = CSharpCompilation.Create("Parameters", [variantTree]).GetSemanticModel(variantTree);
        var variantRows = new List<Occurrence>(); var method = variantTree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().First();
        AddOccurrence(variantRows, Body(method)!, variantModel, new("Fixture.cs", "Fixture.csproj", "shipping", Hash(variant)), "A", "A", 1, "method", 0);
        parameterHashes.Add(variantRows.Single().NormalizedHash);
    }
    if (parameterHashes.Distinct().Count() != 2) throw new Exception("Parameter position changes erased.");
    var capturedHashes = new List<string>();
    foreach (var capture in new[] { "input", "item" })
    {
        var captured = source.Replace("int result = 0;", "System.Func<int, int> f = (int item) => " + capture + "; int result = 0;", StringComparison.Ordinal);
        var capturedTree = CSharpSyntaxTree.ParseText(captured); var capturedModel = CSharpCompilation.Create("Captures", [capturedTree]).GetSemanticModel(capturedTree);
        var capturedRows = new List<Occurrence>(); var method = capturedTree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().First();
        AddOccurrence(capturedRows, Body(method)!, capturedModel, new("Fixture.cs", "Fixture.csproj", "shipping", Hash(captured)), "A", "A", 1, "method", 0);
        capturedHashes.Add(capturedRows.Single().NormalizedHash);
    }
    if (capturedHashes.Distinct().Count() != 2) throw new Exception("Captured outer parameter and lambda parameter conflated.");
    var temp = Path.Combine(Path.GetTempPath(), "excise-duplicates-" + Guid.NewGuid().ToString("N"));
    Directory.CreateDirectory(temp);
    try
    {
        Git(temp, "init", "--quiet");
        foreach (var path in new[] { "architecture/repository-scope.json", "tests/code-health/intentional-duplicates.json", "tools/Excise.DuplicateEvidence/Program.cs" })
        { Directory.CreateDirectory(Path.GetDirectoryName(Path.Combine(temp, path))!); File.Copy(Path.Combine(repository, path), Path.Combine(temp, path)); }
        File.WriteAllText(Path.Combine(temp, "Fixture.csproj"), "<Project />"); File.WriteAllText(Path.Combine(temp, "Fixture.cs"), source);
        File.WriteAllText(Path.Combine(temp, "Generated.g.cs"), source); File.WriteAllText(Path.Combine(temp, "Untracked.cs"), source);
        File.WriteAllText(Path.Combine(temp, "Header.cs"), "// <auto-generated/>\n" + source);
        File.WriteAllText(Path.Combine(temp, "MarkerLiteral.cs"), "class MarkerLiteral { string Text = \"<auto-generated/>\"; }");
        Git(temp, "add", "Fixture.csproj", "Fixture.cs", "Generated.g.cs", "Header.cs", "MarkerLiteral.cs");
        var first = Build(temp, null); var second = Build(temp, null);
        if (Serialize(first) != Serialize(second) || first.Candidates.Length != 1 || !first.Exclusions.Any(e => e.Path == "Generated.g.cs") || first.Inputs.Any(i => i.Path == "Untracked.cs"))
            throw new Exception("Determinism, scope or generated exclusion failed.");
        if (!first.Exclusions.Any(e => e.Path == "Header.cs") || first.Exclusions.Any(e => e.Path == "MarkerLiteral.cs")
            || first.Inputs.Single(i => i.Path == "MarkerLiteral.cs").Classification == "generated") throw new Exception("Generated header versus marker literal scope regression.");
        var independent = Path.Combine(temp, "independent-checkout"); Directory.CreateDirectory(independent); Git(independent, "init", "--quiet");
        foreach (var path in new[] { "architecture/repository-scope.json", "tests/code-health/intentional-duplicates.json", "tools/Excise.DuplicateEvidence/Program.cs", "Fixture.csproj", "Fixture.cs", "Generated.g.cs", "Header.cs", "MarkerLiteral.cs" })
        { Directory.CreateDirectory(Path.GetDirectoryName(Path.Combine(independent, path))!); File.Copy(Path.Combine(temp, path), Path.Combine(independent, path)); }
        Git(independent, "add", "Fixture.csproj", "Fixture.cs", "Generated.g.cs", "Header.cs", "MarkerLiteral.cs");
        if (Serialize(first) != Serialize(Build(independent, null))) throw new Exception("Absolute checkout path changed capture bytes.");
        if (!first.Candidates[0].Occurrences.Single(o => o.Source.MethodName == "A").CallerNameCandidates.Any(c => c.OwnerSymbolKey.Contains(".Use", StringComparison.Ordinal)))
            throw new Exception("Caller lead missing.");
        Directory.CreateDirectory(Path.Combine(temp, "architecture/generated"));
        File.WriteAllText(Path.Combine(temp, "architecture/generated/code-topology.json"), Serialize(new
        {
            sourceRevision = new string('0', 40),
            symbols = new[] { new { kind = "method", file = "Fixture.cs", startLine = 1, symbol = first.Candidates[0].Occurrences.Single(o => o.Source.MethodName == "A").Source.Symbol, reachable = true, fanIn = 1 } }
        }));
        var joined = Build(temp, null);
        if (joined.Candidates[0].Occurrences.Count(o => o.TopologySymbol is not null) != 1 || !joined.Topology.Freshness.StartsWith("source-revision-unavailable", StringComparison.Ordinal))
            throw new Exception("Same-line distinct-symbol join or unavailable topology provenance failed.");
        File.WriteAllText(Path.Combine(temp, "Fixture.cs"), "\n// shift declaration lines\n" + source);
        var shifted = Build(temp, null);
        if (first.Candidates[0].Id != shifted.Candidates[0].Id || shifted.Candidates[0].Occurrences[0].Source.StartLine == first.Candidates[0].Occurrences[0].Source.StartLine)
            throw new Exception("Stable candidate identity/source spans failed.");
        // The same implementation nested inside different enclosing methods must be a block candidate.
        var blockFixture = source.Replace("int result = 0;", "{ int result = 0;", StringComparison.Ordinal)
            .Replace("int total = 0;", "{ int total = 0;", StringComparison.Ordinal)
            .Replace("return result; }", "return result; } }", StringComparison.Ordinal)
            .Replace("return total; }", "return total; } }", StringComparison.Ordinal);
        File.WriteAllText(Path.Combine(temp, "Fixture.cs"), blockFixture);
        if (!Build(temp, null).Candidates.Any(c => c.Kind == "block")) throw new Exception("Planted nested block duplicate missed.");
        File.WriteAllText(Path.Combine(temp, "Fixture.cs"), source);
        var registration = new Registry(1, [new(first.Candidates[0].Id, "https://github.com/marctjones/excise/issues/1941", "Planted intentional duplication", "2026-10-01")]);
        File.WriteAllText(Path.Combine(temp, "tests/code-health/intentional-duplicates.json"), Serialize(registration));
        if (Build(temp, new DateOnly(2026, 10, 4)).Candidates[0].ReviewStatus != "expired-registration; review-required") throw new Exception("Expiry failed.");
        try { Validate(new(1, [registration.Entries[0] with { Issue = "", ReviewBy = "never" }])); throw new Exception("Invalid registry accepted."); }
        catch (InvalidOperationException) { }
        Console.WriteLine("PASS: deterministic captures across independent checkouts; stable candidate IDs/spans; method/block/local-rename duplicates; literal/operator/callee/parameter-position/capture changes non-duplicate; tiny/generated/untracked exclusions; caller and topology links/provenance; registry validation/expiry.");
    }
    finally { Directory.Delete(temp, true); }
}
record Input(string Path, string? Project, string Classification, string Sha256);
record Exclusion(string Path, string Classification, string Reason);
record Occurrence(string Id, string SymbolKey, string Symbol, string MethodName, string Project, string Classification, string Path, int MethodStartLine, int StartLine, int StartColumn, int EndLine, int EndColumn, string Kind, string ExactHash, string NormalizedHash, [property: JsonIgnore] string[] Tokens);
record Caller(string OwnerSymbolKey, string Path, int Line, string TargetName);
record Evidence(Occurrence Source, Caller[] CallerNameCandidates, JsonElement? TopologySymbol, string TopologyJoinStatus);
record Registration(string CandidateId, string Issue, string Rationale, string ReviewBy);
record Registry(int SchemaVersion, Registration[] Entries);
record Candidate(string Id, string Kind, string Match, string NormalizedHash, string[] NormalizedTokens, string ReviewStatus, Registration? Registration, Evidence[] Occurrences);
record TopologyProvenance(string? Sha256, string? SourceRevision, string Freshness, string Reproduce);
record Report(int SchemaVersion, string ToolVersion, string ToolSourceHash, string RoslynVersion, string ScopeHash, string RegistryHash, string? ReviewDate, string NormalizationContract, string ScopeContract, string ReviewContract, string Reproduce, TopologyProvenance Topology, Input[] Inputs, Exclusion[] Exclusions, string[] UnmatchedRegistrations, Candidate[] Candidates);
