using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

// Deterministic declaration evidence only; no quality verdict. See #1939.
var root = Path.GetFullPath(args.Length > 1 ? args[1] : ".");
if (args.Length == 0 || args[0] is not ("inventory" or "compare" or "self-test"))
    throw new ArgumentException("Usage: inventory ROOT OUTPUT | compare ROOT BEFORE AFTER OUTPUT | self-test ROOT");
if (args[0] == "self-test")
{
    SelfTest(root);
    return;
}
if (args[0] == "compare")
{
    var before = JsonSerializer.Deserialize<Inventory>(File.ReadAllText(args[2]))!;
    var after = JsonSerializer.Deserialize<Inventory>(File.ReadAllText(args[3]))!;
    File.WriteAllText(args[4], Serialize(Compare(before, after)), new UTF8Encoding(false));
    return;
}
File.WriteAllText(args[2], Serialize(Build(root)), new UTF8Encoding(false));

static string Serialize(object value)
{
    // One declaration/input per line keeps a large baseline diff reviewable without repeated indentation.
    if (value is Inventory inventory)
    {
        var json = JsonSerializer.SerializeToNode(inventory)!;
        var rows = new List<string> { "{" };
        foreach (var property in json.AsObject())
        {
            var name = JsonSerializer.Serialize(property.Key);
            if (property.Value is System.Text.Json.Nodes.JsonArray array)
                rows.Add("  " + name + ": [\n" + string.Join(",\n", array.Select(row => "    " + row!.ToJsonString())) + "\n  ]");
            else rows.Add("  " + name + ": " + property.Value!.ToJsonString());
            rows[^1] += ",";
        }
        rows[^1] = rows[^1][..^1];
        rows.Add("}");
        return string.Join("\n", rows) + "\n";
    }
    return JsonSerializer.Serialize(value, new JsonSerializerOptions { WriteIndented = true }) + "\n";
}
static string Hash(string value) => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(value)));
static string Normalize(string value) => value.Replace("\r\n", "\n").Replace('\r', '\n');
static bool HasGeneratedHeader(string source)
{
    // Only leading comment trivia is a header; code/literals and directives
    // terminate the header region. See #1939.
    var trivia = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.CSharp14)).GetRoot().GetFirstToken(includeZeroWidth: true).LeadingTrivia;
    foreach (var item in trivia)
    {
        if (item.IsKind(SyntaxKind.WhitespaceTrivia) || item.IsKind(SyntaxKind.EndOfLineTrivia)) continue;
        if (item.Kind() is not (SyntaxKind.SingleLineCommentTrivia or SyntaxKind.MultiLineCommentTrivia
            or SyntaxKind.SingleLineDocumentationCommentTrivia or SyntaxKind.MultiLineDocumentationCommentTrivia)) return false;
        if (item.ToFullString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) return true;
    }
    return false;
}
static string Git(string root, params string[] arguments)
{
    var start = new ProcessStartInfo("git") { WorkingDirectory = root, RedirectStandardOutput = true, RedirectStandardError = true };
    foreach (var argument in arguments) start.ArgumentList.Add(argument);
    using var process = Process.Start(start)!;
    var output = process.StandardOutput.ReadToEnd();
    var error = process.StandardError.ReadToEnd();
    process.WaitForExit();
    if (process.ExitCode != 0) throw new InvalidOperationException(error);
    return output;
}
static Inventory Build(string root)
{
    var tracked = Git(root, "ls-files", "-z").Split('\0', StringSplitOptions.RemoveEmptyEntries).Order(StringComparer.Ordinal).ToArray();
    var projects = tracked.Where(p => p.EndsWith(".csproj", StringComparison.Ordinal)).ToArray();
    var scopeText = Normalize(File.ReadAllText(Path.Combine(root, "architecture/repository-scope.json")));
    using var scope = JsonDocument.Parse(scopeText);
    var files = new List<Input>();
    var excluded = new List<Exclusion>();
    var symbols = new List<Declaration>();
    foreach (var path in tracked.Where(p => p.EndsWith(".cs", StringComparison.Ordinal)))
    {
        var absolute = Path.Combine(root, path);
        if (!File.Exists(absolute)) throw new InvalidOperationException($"Tracked input missing: {path}. Commit removals before generating a baseline.");
        var source = Normalize(File.ReadAllText(absolute));
        var classification = "shipping";
        string? reason = null;
        foreach (var group in new[] { "excludedRoots", "reviewOnlyRoots" })
        foreach (var rule in scope.RootElement.GetProperty(group).EnumerateArray())
        {
            var prefix = rule.GetProperty("path").GetString()!;
            if (path == prefix || path.StartsWith(prefix + "/", StringComparison.Ordinal)
                || (prefix is "bin" or "obj" && path.Split('/').Contains(prefix)))
            {
                classification = rule.GetProperty("classification").GetString()!;
                reason = rule.GetProperty("reason").GetString();
            }
        }
        var project = projects.Where(p => path.StartsWith(p[..(p.LastIndexOf('/') + 1)], StringComparison.Ordinal))
            .OrderByDescending(p => p.LastIndexOf('/')).ThenBy(p => p, StringComparer.Ordinal).FirstOrDefault();
        if (reason is null && project is null) { classification = "unowned"; reason = "No tracked ancestor project."; }
        if (reason is null)
        {
            classification = scope.RootElement.GetProperty("defaultProjectClassification").GetString()!;
            foreach (var rule in scope.RootElement.GetProperty("projectRules").EnumerateArray())
            {
                var pattern = "^" + Regex.Escape(rule.GetProperty("pattern").GetString()!).Replace("\\*", ".*") + "$";
                if (Regex.IsMatch(project!, pattern, RegexOptions.CultureInvariant))
                { classification = rule.GetProperty("classification").GetString()!; break; }
            }
            if (path.EndsWith(".g.cs", StringComparison.Ordinal) || path.EndsWith(".generated.cs", StringComparison.Ordinal)
                || HasGeneratedHeader(source))
            { classification = "generated"; reason = "Generated filename or auto-generated header."; }
        }
        files.Add(new(path, project, classification, Hash(source)));
        if (reason is not null) { excluded.Add(new(path, classification, reason)); continue; }
    }
    foreach (var group in files.Where(f => !excluded.Any(e => e.Path == f.Path)).GroupBy(f => f.Project).OrderBy(g => g.Key, StringComparer.Ordinal))
    {
        var trees = group.Select(f => CSharpSyntaxTree.ParseText(Normalize(File.ReadAllText(Path.Combine(root, f.Path))),
            new CSharpParseOptions(LanguageVersion.CSharp14), f.Path)).ToArray();
        foreach (var tree in trees)
            if (tree.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error))
                throw new InvalidOperationException($"Syntax errors in {tree.FilePath}; inventory must not silently omit declarations.");
        // No reference binding or MSBuild evaluation; inactive preprocessor branches are not symbols.
        var compilation = CSharpCompilation.Create("Inventory", trees);
        foreach (var tree in trees)
        {
            var model = compilation.GetSemanticModel(tree);
            var input = group.Single(f => f.Path == tree.FilePath);
            foreach (var node in tree.GetRoot().DescendantNodes().Where(n => n is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax
                or BaseMethodDeclarationSyntax or PropertyDeclarationSyntax or IndexerDeclarationSyntax
                or EventDeclarationSyntax or VariableDeclaratorSyntax or EnumMemberDeclarationSyntax))
            {
                var symbol = model.GetDeclaredSymbol(node);
                if (symbol is null || symbol.Kind is not (SymbolKind.NamedType or SymbolKind.Method or SymbolKind.Property or SymbolKind.Field or SymbolKind.Event)) continue;
                var id = symbol.GetDocumentationCommentId();
                if (id is null) continue;
                var location = node.GetLocation().GetLineSpan();
                symbols.Add(new(input.Project! + "::" + id, id, symbol.Kind.ToString(), input.Project!, input.Classification,
                    tree.FilePath, location.StartLinePosition.Line + 1, Hash(node.ToFullString()), input.SourceHash));
            }
        }
    }
    return new(1, "Excise.CodeHealth/1", Hash(Normalize(File.ReadAllText(Path.Combine(root, "tools/Excise.CodeHealth/Program.cs")))) , typeof(CSharpCompilation).Assembly.GetName().Version!.ToString(),
        "CSharp14; no references; default preprocessor symbols; declaration syntax only", Hash(scopeText),
        "dotnet run --project tools/Excise.CodeHealth -- inventory . tests/code-health/symbols.json",
        "git ls-files -z; tracked *.cs and nearest tracked ancestor *.csproj; LF-normalized UTF-8 SHA-256",
        files.ToArray(), excluded.ToArray(), symbols.OrderBy(s => s.Key, StringComparer.Ordinal).ThenBy(s => s.Path, StringComparer.Ordinal).ThenBy(s => s.Line).ToArray());
}
static Delta Compare(Inventory before, Inventory after)
{
    var old = before.Symbols.GroupBy(s => s.Key).ToDictionary(g => g.Key, g => Serialize(g.ToArray()));
    var current = after.Symbols.GroupBy(s => s.Key).ToDictionary(g => g.Key, g => Serialize(g.ToArray()));
    return new(1, "Renamed identifiers are removed+added; retained identifiers with new paths are changed. Partial declarations share a key.",
        current.Keys.Except(old.Keys).Order(StringComparer.Ordinal).ToArray(), old.Keys.Except(current.Keys).Order(StringComparer.Ordinal).ToArray(),
        current.Keys.Intersect(old.Keys).Where(k => current[k] != old[k]).Order(StringComparer.Ordinal).ToArray());
}
static void SelfTest(string repository)
{
    foreach (var source in new[] { "class Marker { string Text = \"<auto-generated/>\"; }", "class Marker {} // <auto-generated/>", "#nullable enable\n// <auto-generated/>\nclass Marker {}" })
        if (HasGeneratedHeader(source)) throw new Exception("Non-header generated marker excluded source.");
    foreach (var source in new[] { " \n// license\n// <auto-generated/>\nclass Marker {}", "/* <AUTO-GENERATED> */\nclass Marker {}" })
        if (!HasGeneratedHeader(source)) throw new Exception("Leading generated comment header missed.");
    var temp = Path.Combine(Path.GetTempPath(), "excise-code-health-" + Guid.NewGuid().ToString("N"));
    Directory.CreateDirectory(Path.Combine(temp, "architecture"));
    try
    {
        Git(temp, "init", "--quiet");
        File.Copy(Path.Combine(repository, "architecture/repository-scope.json"), Path.Combine(temp, "architecture/repository-scope.json"));
        Directory.CreateDirectory(Path.Combine(temp, "tools/Excise.CodeHealth"));
        File.Copy(Path.Combine(repository, "tools/Excise.CodeHealth/Program.cs"), Path.Combine(temp, "tools/Excise.CodeHealth/Program.cs"));
        File.WriteAllText(Path.Combine(temp, "Fixture.csproj"), "<Project />");
        File.WriteAllText(Path.Combine(temp, "Fixture.cs"), "namespace Sample; public partial class Example { public int Before() => 1; }");
        File.WriteAllText(Path.Combine(temp, "Generated.g.cs"), "class Generated {}");
        File.WriteAllText(Path.Combine(temp, "Header.cs"), "// <auto-generated/>\nclass Header {}");
        File.WriteAllText(Path.Combine(temp, "MarkerLiteral.cs"), "class MarkerLiteral { string Text = \"<auto-generated/>\"; }");
        File.WriteAllText(Path.Combine(temp, "Untracked.cs"), "class Untracked {}");
        Git(temp, "add", "architecture/repository-scope.json", "Fixture.csproj", "Fixture.cs", "Generated.g.cs", "Header.cs", "MarkerLiteral.cs");
        var before = Build(temp);
        if (Serialize(before) != Serialize(Build(temp))) throw new Exception("Repeated inventory differs.");
        var second = Path.Combine(temp, "second-checkout");
        Directory.CreateDirectory(Path.Combine(second, "architecture"));
        Directory.CreateDirectory(Path.Combine(second, "tools/Excise.CodeHealth"));
        Git(second, "init", "--quiet");
        foreach (var path in new[] { "architecture/repository-scope.json", "Fixture.csproj", "Fixture.cs", "Generated.g.cs", "Header.cs", "MarkerLiteral.cs", "tools/Excise.CodeHealth/Program.cs" })
            File.Copy(Path.Combine(temp, path), Path.Combine(second, path));
        Git(second, "add", "architecture/repository-scope.json", "Fixture.csproj", "Fixture.cs", "Generated.g.cs", "Header.cs", "MarkerLiteral.cs");
        if (Serialize(before) != Serialize(Build(second))) throw new Exception("Independent checkout paths changed inventory bytes.");
        if (!before.Exclusions.Any(e => e.Classification == "generated") || before.Inputs.Any(f => f.Path == "Untracked.cs")) throw new Exception("Scope filtering failed.");
        if (!before.Exclusions.Any(e => e.Path == "Header.cs") || before.Exclusions.Any(e => e.Path == "MarkerLiteral.cs")
            || !before.Symbols.Any(s => s.Path == "MarkerLiteral.cs")) throw new Exception("Generated header versus marker literal scope regression.");
        File.WriteAllText(Path.Combine(temp, "Fixture.cs"), "namespace Sample; public partial class Example { public int After() => 1; }");
        var delta = Compare(before, Build(temp));
        if (!delta.Added.Any(k => k.EndsWith(".After", StringComparison.Ordinal)) || !delta.Removed.Any(k => k.EndsWith(".Before", StringComparison.Ordinal))) throw new Exception("Planted rename/add/remove missed.");
        Git(temp, "mv", "Fixture.cs", "Renamed.cs");
        if (!Compare(before, Build(temp)).Changed.Any(k => k.EndsWith("Sample.Example", StringComparison.Ordinal))) throw new Exception("Relocation missed.");
        Git(temp, "rm", "--force", "Renamed.cs");
        if (!Compare(before, Build(temp)).Removed.Any(k => k.EndsWith("Sample.Example", StringComparison.Ordinal))) throw new Exception("Deleted type missed.");
        Console.WriteLine("PASS: deterministic bytes across independent checkouts; tracked scope; generated exclusion; added/removed/renamed/relocated/deleted symbols.");
    }
    finally { Directory.Delete(temp, true); }
}
record Input(string Path, string? Project, string Classification, string SourceHash);
record Exclusion(string Path, string Classification, string Reason);
record Declaration(string Key, string FullyQualifiedSymbol, string Kind, string Project, string Classification, string Path, int Line, string DeclarationHash, string SourceHash);
record Inventory(int SchemaVersion, string ToolVersion, string ToolSourceHash, string RoslynVersion, string ParseContract, string ScopeHash, string Reproduce, string InputContract, Input[] Inputs, Exclusion[] Exclusions, Declaration[] Symbols);
record Delta(int SchemaVersion, string RenameContract, string[] Added, string[] Removed, string[] Changed);
