using System.Text;
using System.Text.RegularExpressions;
using Excise.Core.Document;
using Excise.Core.Parsing;
using Excise.Core.Primitives;
using Excise.Core.Writing;

namespace Excise.Core.Forms;

/// <summary>
/// Result of importing an FDF annotation file into a document.
/// </summary>
public sealed class FdfImportResult
{
    /// <summary>The annotations that were added to the document, re-read from their pages.</summary>
    public IReadOnlyList<PdfAnnotation> Imported { get; }

    /// <summary>
    /// Human-readable descriptions of FDF annotation dictionaries that were
    /// present but not imported (unsupported subtype, missing required
    /// geometry, page out of range). Empty when everything was imported.
    /// </summary>
    public IReadOnlyList<string> Skipped { get; }

    internal FdfImportResult(IReadOnlyList<PdfAnnotation> imported, IReadOnlyList<string> skipped)
    {
        Imported = imported;
        Skipped = skipped;
    }
}

/// <summary>
/// FDF (Forms Data Format) annotation import/export — the PDF-syntax
/// counterpart to <see cref="XfdfSerializer"/> (#626). Grammar follows
/// ISO 32000-1 §12.7.7: a body of indirect objects headed by
/// <c>%FDF-1.2</c>, a catalog whose <c>/FDF</c> dictionary carries an
/// <c>/Annots</c> array of annotation dictionaries (each with a 0-based
/// <c>/Page</c> entry instead of a page attachment), and a trailer whose
/// <c>/Root</c> points at the catalog. Because FDF reuses PDF object syntax,
/// annotation entries (<c>/Rect</c>, <c>/C</c>, <c>/QuadPoints</c>,
/// <c>/InkList</c>, …) appear exactly as they do inside a PDF.
/// </summary>
/// <remarks>
/// <para>
/// <b>Export</b> covers the same subtypes as <see cref="XfdfSerializer"/>:
/// Text, FreeText, Line, Square, Circle, Polygon, PolyLine, Highlight,
/// Underline, Squiggly, StrikeOut, Stamp, Caret, Ink, Watermark and Redact.
/// Link, Popup, Widget, FileAttachment, Sound, Movie and Screen annotations
/// are not exported — links and widgets are document structure (widget data
/// belongs to the FDF <c>/Fields</c> form-data section, not to comments),
/// and popups are regenerated by the consuming viewer.
/// </para>
/// <para>
/// <b>Import</b> supports Text, FreeText, Line, Square, Circle, Polygon,
/// PolyLine, Highlight, Underline, Squiggly, StrikeOut, Caret and Ink
/// dictionaries. Subtypes with an authoring method
/// (<see cref="PdfAnnotationAuthoring"/>) are created through it so they get
/// a baked <c>/AP</c> appearance stream; the remainder are written as
/// spec-correct dictionaries without an appearance (viewers synthesize one,
/// as they do for Acrobat's own AP-less markup). Unknown subtypes are
/// reported in <see cref="FdfImportResult.Skipped"/>, never an error.
/// </para>
/// </remarks>
public static class FdfSerializer
{
    /// <summary>The FDF header comment line (ISO 32000-1 §12.7.8: version 1.2).</summary>
    public const string FdfHeader = "%FDF-1.2";

    // ── Export ────────────────────────────────────────────────────────────────

    /// <summary>
    /// Serialize all exportable annotations of <paramref name="document"/> to
    /// an FDF string. The output contains only ASCII characters (non-ASCII
    /// string bytes are octal-escaped by the PDF writer), so the string and
    /// stream overloads are byte-for-byte equivalent.
    /// </summary>
    public static string ExportAnnotations(PdfDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);
        return BuildFdf(document);
    }

    /// <summary>
    /// Serialize all exportable annotations of <paramref name="document"/> as
    /// FDF bytes to <paramref name="output"/>. The stream is left open.
    /// </summary>
    public static void ExportAnnotations(PdfDocument document, Stream output)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(output);

        var bytes = Encoding.Latin1.GetBytes(BuildFdf(document));
        output.Write(bytes, 0, bytes.Length);
    }

    private static string BuildFdf(PdfDocument document)
    {
        var annots = new List<PdfDictionary>();

        int pageIndex = 0;
        foreach (var page in document.GetPages())
        {
            foreach (var annotation in page.GetAnnotations())
            {
                var dict = ExportOne(document, annotation, pageIndex);
                if (dict != null)
                    annots.Add(dict);
            }
            pageIndex++;
        }

        // Catalog is object 1; each annotation is its own indirect object
        // (2..N+1), the shape Acrobat writes and every FDF reader expects.
        var annotsArray = new PdfArray();
        for (int i = 0; i < annots.Count; i++)
            annotsArray.Add(new PdfReference(i + 2, 0));

        var fdfDict = new PdfDictionary();
        fdfDict["Annots"] = annotsArray;
        var catalog = new PdfDictionary();
        catalog["FDF"] = fdfDict;

        var sb = new StringBuilder();
        sb.Append(FdfHeader).Append('\n');
        AppendIndirectObject(sb, 1, catalog);
        for (int i = 0; i < annots.Count; i++)
            AppendIndirectObject(sb, i + 2, annots[i]);

        var trailer = new PdfDictionary();
        trailer["Root"] = new PdfReference(1, 0);
        sb.Append("trailer\n");
        PdfObjectWriter.SerializeObject(trailer, sb);
        sb.Append("\n%%EOF\n");
        return sb.ToString();
    }

    private static void AppendIndirectObject(StringBuilder sb, int objectNumber, PdfObject value)
    {
        sb.Append(objectNumber).Append(" 0 obj\n");
        PdfObjectWriter.SerializeObject(value, sb);
        sb.Append("\nendobj\n");
    }

    private static PdfDictionary? ExportOne(PdfDocument document, PdfAnnotation a, int pageIndex)
    {
        var subtype = a.Subtype switch
        {
            PdfAnnotationSubtype.Text      => "Text",
            PdfAnnotationSubtype.FreeText  => "FreeText",
            PdfAnnotationSubtype.Line      => "Line",
            PdfAnnotationSubtype.Square    => "Square",
            PdfAnnotationSubtype.Circle    => "Circle",
            PdfAnnotationSubtype.Polygon   => "Polygon",
            PdfAnnotationSubtype.PolyLine  => "PolyLine",
            PdfAnnotationSubtype.Highlight => "Highlight",
            PdfAnnotationSubtype.Underline => "Underline",
            PdfAnnotationSubtype.Squiggly  => "Squiggly",
            PdfAnnotationSubtype.StrikeOut => "StrikeOut",
            PdfAnnotationSubtype.Stamp     => "Stamp",
            PdfAnnotationSubtype.Caret     => "Caret",
            PdfAnnotationSubtype.Ink       => "Ink",
            PdfAnnotationSubtype.Watermark => "Watermark",
            PdfAnnotationSubtype.Redact    => "Redact",
            _ => null // Link/Popup/Widget/FileAttachment/Sound/Movie/Screen/Unknown
        };
        if (subtype == null)
            return null;

        var src = a.RawDictionary;
        var dict = new PdfDictionary();
        dict.SetName("Type", "Annot");
        dict.SetName("Subtype", subtype);
        dict.SetInt("Page", pageIndex); // FDF-specific: 0-based page (§12.7.7.3.3)
        dict["Rect"] = PdfArray.FromRectangle(a.Rect.Left, a.Rect.Bottom, a.Rect.Right, a.Rect.Top);

        if (a.Color is { } c)
            dict["C"] = new PdfArray(new PdfReal(c.R), new PdfReal(c.G), new PdfReal(c.B));
        if (ResolveArray(document, src, "IC") is { Count: 3 } ic)
            dict["IC"] = CopyNumberArray(ic);

        if (a.Flags != PdfAnnotationFlags.None)
            dict.SetInt("F", (int)a.Flags);

        SetString(dict, "NM", a.Name);
        SetString(dict, "T", a.Author);
        SetString(dict, "Subj", ResolveString(document, src, "Subj"));
        SetString(dict, "M", ResolveString(document, src, "M"));
        SetString(dict, "CreationDate", ResolveString(document, src, "CreationDate"));

        if (ResolveNumber(document, src, "CA") is { } opacity)
            dict.SetNumber("CA", opacity);

        if (a.BorderWidth != null || a.BorderStyle != null || a.BorderDashPattern is { Count: > 0 })
        {
            var bs = new PdfDictionary();
            bs.SetName("Type", "Border");
            if (a.BorderWidth is { } width)
                bs.SetNumber("W", width);
            bs.SetName("S", a.BorderStyle ?? (a.BorderDashPattern is { Count: > 0 } ? "D" : "S"));
            if (a.BorderDashPattern is { Count: > 0 } dashes)
            {
                var d = new PdfArray();
                foreach (var v in dashes)
                    d.Add(v);
                bs["D"] = d;
            }
            dict["BS"] = bs;
        }

        // ── Subtype-specific geometry ─────────────────────────────────────────

        if (a.IsTextMarkup || a.Subtype == PdfAnnotationSubtype.Redact)
        {
            // Raw /QuadPoints keeps the exact 8-number quads (the read model
            // collapses them to bounding boxes).
            if (ResolveArray(document, src, "QuadPoints") is { Count: >= 8 } qp)
                dict["QuadPoints"] = CopyNumberArray(qp);
        }

        if (a.LineEndpoints is { } line)
            dict["L"] = new PdfArray(
                new PdfReal(line.X1), new PdfReal(line.Y1),
                new PdfReal(line.X2), new PdfReal(line.Y2));

        if (a.Vertices is { Count: > 0 } vertices)
        {
            var arr = new PdfArray();
            foreach (var (x, y) in vertices)
            {
                arr.Add(x);
                arr.Add(y);
            }
            dict["Vertices"] = arr;
        }

        if (a.InkStrokes is { Count: > 0 } strokes)
        {
            var inkList = new PdfArray();
            foreach (var stroke in strokes)
            {
                var gesture = new PdfArray();
                foreach (var (x, y) in stroke)
                {
                    gesture.Add(x);
                    gesture.Add(y);
                }
                inkList.Add(gesture);
            }
            dict["InkList"] = inkList;
        }

        if (a.Subtype is PdfAnnotationSubtype.Text or PdfAnnotationSubtype.Stamp)
        {
            if (!string.IsNullOrEmpty(a.IconName))
                dict.SetName("Name", a.IconName);
            if (a.Subtype == PdfAnnotationSubtype.Text)
                dict.SetBool("Open", a.IsOpen);
        }

        if (a.Subtype == PdfAnnotationSubtype.FreeText)
        {
            if (src.GetInt("Q", 0) is var q and > 0)
                dict.SetInt("Q", q);
            if (ResolveString(document, src, "DA") is { } da)
                dict.SetString("DA", da);
        }

        if (!string.IsNullOrEmpty(a.Contents))
            dict.SetString("Contents", a.Contents);

        return dict;
    }

    // ── Import ────────────────────────────────────────────────────────────────

    /// <summary>
    /// Parse <paramref name="fdf"/> and add the annotations it describes to
    /// <paramref name="document"/>.
    /// </summary>
    /// <exception cref="PdfParseException">The input is not parseable PDF syntax.</exception>
    /// <exception cref="InvalidDataException">The input parses but is not an
    /// FDF document (no catalog with an <c>/FDF</c> dictionary).</exception>
    public static FdfImportResult ImportAnnotations(PdfDocument document, string fdf)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(fdf);

        return ImportCore(document, Encoding.Latin1.GetBytes(fdf));
    }

    /// <summary>
    /// Parse FDF bytes from <paramref name="input"/> and add the annotations
    /// they describe to <paramref name="document"/>. The stream is left open.
    /// </summary>
    /// <exception cref="PdfParseException">The input is not parseable PDF syntax.</exception>
    /// <exception cref="InvalidDataException">The input parses but is not an
    /// FDF document (no catalog with an <c>/FDF</c> dictionary).</exception>
    public static FdfImportResult ImportAnnotations(PdfDocument document, Stream input)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(input);

        using var ms = new MemoryStream();
        input.CopyTo(ms);
        return ImportCore(document, ms.ToArray());
    }

    private static FdfImportResult ImportCore(PdfDocument document, byte[] bytes)
    {
        var (objects, trailer) = ParseBody(bytes);
        var fdfDict = FindFdfDictionary(objects, trailer)
            ?? throw new InvalidDataException(
                "Not an FDF document: no catalog with an /FDF dictionary was found.");

        var skipped = new List<string>();
        var added = new List<(int PageNumber, PdfDictionary Dictionary)>();

        if (Resolve(fdfDict.GetOptional("Annots"), objects) is PdfArray annots)
        {
            foreach (var entry in annots)
            {
                if (Resolve(entry, objects) is not PdfDictionary raw)
                {
                    skipped.Add("(non-dictionary /Annots entry): unsupported annotation type");
                    continue;
                }

                var annot = DeepResolve(raw, objects, depth: 0) as PdfDictionary ?? raw;
                var subtype = annot.GetNameOrNull("Subtype") ?? "(no subtype)";
                try
                {
                    var result = ImportOne(document, annot, subtype);
                    if (result is { } ok)
                        added.Add(ok);
                    else
                        skipped.Add(DescribeSkip(annot, subtype, "unsupported annotation type"));
                }
                catch (FdfSkipException skip)
                {
                    skipped.Add(DescribeSkip(annot, subtype, skip.Message));
                }
            }
        }

        // Re-read the freshly attached annotations so the returned models
        // reflect every entry (NM, dates, flags) applied after authoring.
        var imported = new List<PdfAnnotation>(added.Count);
        foreach (var pageGroup in added.GroupBy(x => x.PageNumber))
        {
            var pageAnnotations = document.GetPage(pageGroup.Key).GetAnnotations();
            foreach (var (_, dictionary) in pageGroup)
            {
                var model = pageAnnotations.FirstOrDefault(x => ReferenceEquals(x.RawDictionary, dictionary));
                if (model != null)
                    imported.Add(model);
            }
        }

        return new FdfImportResult(imported, skipped);
    }

    /// <summary>
    /// Parse the FDF body: every indirect object plus the trailer dictionary.
    /// FDF files need no cross-reference table (§12.7.8), so the body is read
    /// sequentially; stray xref/startxref material between objects is skipped.
    /// </summary>
    private static (Dictionary<int, PdfObject> Objects, PdfDictionary? Trailer) ParseBody(byte[] bytes)
    {
        var objects = new Dictionary<int, PdfObject>();
        PdfDictionary? trailer = null;

        using var parser = new PdfParser(bytes);
        while (true)
        {
            var indirect = parser.TryParseIndirectObject();
            if (indirect != null)
            {
                objects[indirect.ObjectNumber] = indirect.Value;
                continue;
            }

            var token = parser.Lexer.NextToken();
            if (token.IsEof)
                break;
            if (token.IsKeyword("trailer") && parser.ParseObject() is PdfDictionary t)
                trailer = t;
            // Any other token (xref rows, startxref offsets) is skipped.
        }

        if (objects.Count == 0 && trailer == null)
            throw new PdfParseException("No PDF objects found in FDF input.");

        return (objects, trailer);
    }

    private static PdfDictionary? FindFdfDictionary(
        Dictionary<int, PdfObject> objects, PdfDictionary? trailer)
    {
        // Preferred path: trailer /Root → catalog → /FDF.
        if (trailer != null &&
            Resolve(trailer.GetOptional("Root"), objects) is PdfDictionary catalog &&
            Resolve(catalog.GetOptional("FDF"), objects) is PdfDictionary fromRoot)
            return fromRoot;

        // Tolerant fallback: any body object that carries /FDF.
        foreach (var obj in objects.Values)
        {
            if (obj is PdfDictionary dict &&
                Resolve(dict.GetOptional("FDF"), objects) is PdfDictionary fdf)
                return fdf;
        }
        return null;
    }

    private static PdfObject? Resolve(PdfObject? obj, Dictionary<int, PdfObject> objects)
    {
        for (int i = 0; obj is PdfReference reference; i++)
        {
            if (i > 32 || !objects.TryGetValue(reference.ObjectNum, out obj))
                return null;
        }
        return obj;
    }

    /// <summary>
    /// Replace indirect references inside <paramref name="obj"/> with their
    /// resolved values so annotation entries can be read directly. Bounded
    /// depth guards against reference cycles.
    /// </summary>
    private static PdfObject DeepResolve(PdfObject obj, Dictionary<int, PdfObject> objects, int depth)
    {
        if (depth > 32)
            return obj;

        switch (obj)
        {
            case PdfReference:
                var resolved = Resolve(obj, objects);
                return resolved == null ? PdfNull.Instance : DeepResolve(resolved, objects, depth + 1);

            case PdfArray array:
                for (int i = 0; i < array.Count; i++)
                    array[i] = DeepResolve(array[i], objects, depth + 1);
                return array;

            case PdfDictionary dict:
                foreach (var key in dict.Keys.ToList())
                    dict[key] = DeepResolve(dict[key], objects, depth + 1);
                return dict;

            default:
                return obj;
        }
    }

    private static string DescribeSkip(PdfDictionary annot, string subtype, string reason)
    {
        var name = annot.GetStringOrNull("NM");
        return name == null ? $"{subtype}: {reason}" : $"{subtype} \"{name}\": {reason}";
    }

    /// <summary>Signals that a single FDF annotation cannot be imported (recorded, not fatal).</summary>
    private sealed class FdfSkipException(string message) : Exception(message);

    private static (int PageNumber, PdfDictionary Dictionary)? ImportOne(
        PdfDocument document, PdfDictionary annot, string subtype)
    {
        int pageIndex = annot.GetInt("Page", 0);
        int pageNumber = pageIndex + 1;
        if (pageNumber < 1 || pageNumber > document.Pages.Count)
            throw new FdfSkipException($"page {pageIndex} out of range (document has {document.Pages.Count} pages)");

        var rect = ReadRect(annot);
        var color = ReadColor(annot, "C");
        var interior = ReadColor(annot, "IC");
        var contents = annot.GetStringOrNull("Contents");
        var author = annot.GetStringOrNull("T");
        double? width =
            annot.GetDictionaryOrNull("BS") is { } bsDict &&
            bsDict.GetOptional("W") is { } widthObj && widthObj.TryGetNumber(out var w)
                ? w : null;

        PdfAnnotation created;
        switch (subtype)
        {
            case "Text":
            {
                var r = RequireRect(rect);
                var icon = annot.GetNameOrNull("Name");
                bool open = annot.GetBool("Open");
                if (!string.IsNullOrWhiteSpace(contents))
                {
                    created = document.AddTextAnnotation(
                        pageNumber, r, contents!, author, open,
                        string.IsNullOrWhiteSpace(icon) ? "Note" : icon!);
                }
                else
                {
                    var dict = NewImportDict("Text", r);
                    dict.SetBool("Open", open);
                    dict.SetName("Name", string.IsNullOrWhiteSpace(icon) ? "Note" : icon!);
                    created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                }
                if (color is { } tc)
                    created.RawDictionary["C"] = ColorArray(tc);
                break;
            }

            case "Square":
            case "Circle":
            {
                var r = RequireRect(rect);
                bool isCircle = subtype == "Circle";
                var stroke = color ?? (1, 0, 0);
                double borderWidth = width ?? 1;
                if (borderWidth > 0 || interior != null)
                {
                    created = isCircle
                        ? document.AddCircleAnnotation(
                            pageNumber, r, contents, author,
                            stroke.Item1, stroke.Item2, stroke.Item3, borderWidth,
                            interior?.Item1, interior?.Item2, interior?.Item3)
                        : document.AddSquareAnnotation(
                            pageNumber, r, contents, author,
                            stroke.Item1, stroke.Item2, stroke.Item3, borderWidth,
                            interior?.Item1, interior?.Item2, interior?.Item3);
                }
                else
                {
                    // Zero border and no fill: legal but invisible — keep the
                    // data without an appearance stream.
                    var dict = NewImportDict(subtype, r);
                    dict["C"] = ColorArray(stroke);
                    created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                }
                break;
            }

            case "FreeText":
            {
                var r = RequireRect(rect);
                if (string.IsNullOrWhiteSpace(contents))
                    throw new FdfSkipException("FreeText without /Contents text");

                var (textColor, fontSize) = ParseDefaultAppearance(annot.GetStringOrNull("DA"));
                var quadding = annot.GetInt("Q", 0) switch
                {
                    1 => PdfFreeTextQuadding.Centered,
                    2 => PdfFreeTextQuadding.RightJustified,
                    _ => PdfFreeTextQuadding.LeftJustified
                };
                created = document.AddFreeTextAnnotation(
                    pageNumber, r, contents!, author, fontSize,
                    textColor.R, textColor.G, textColor.B, quadding,
                    borderWidth: width ?? 0,
                    backgroundRed: color?.Item1,
                    backgroundGreen: color?.Item2,
                    backgroundBlue: color?.Item3);
                break;
            }

            case "Ink":
            {
                var strokes = ReadInkList(annot);
                if (strokes.Count == 0)
                    throw new FdfSkipException("Ink without a usable /InkList gesture");
                var stroke = color ?? (0, 0, 0);
                created = document.AddInkAnnotation(
                    pageNumber, strokes, contents, author,
                    stroke.Item1, stroke.Item2, stroke.Item3, width ?? 2);
                break;
            }

            case "Highlight":
            case "Underline":
            case "Squiggly":
            case "StrikeOut":
            {
                var r = RequireRect(rect);
                var dict = NewImportDict(subtype, r);
                dict["QuadPoints"] = ReadQuadPointsOrDefault(annot, r);
                if (color is { } mc)
                    dict["C"] = ColorArray(mc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            case "Line":
            {
                var line = ReadNumbers(annot, "L");
                if (line is not { Count: >= 4 })
                    throw new FdfSkipException("Line without an /L endpoint array");
                var r = rect ?? new PdfRectangle(
                    Math.Min(line[0], line[2]), Math.Min(line[1], line[3]),
                    Math.Max(line[0], line[2]), Math.Max(line[1], line[3]));
                var dict = NewImportDict("Line", r);
                dict["L"] = new PdfArray(
                    new PdfReal(line[0]), new PdfReal(line[1]),
                    new PdfReal(line[2]), new PdfReal(line[3]));
                if (color is { } lc)
                    dict["C"] = ColorArray(lc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            case "Polygon":
            case "PolyLine":
            {
                var points = ReadNumbers(annot, "Vertices");
                if (points is not { Count: >= 4 })
                    throw new FdfSkipException($"{subtype} without a /Vertices array");
                var r = rect ?? BoundsOf(points);
                var dict = NewImportDict(subtype, r);
                var vertices = new PdfArray();
                foreach (var v in points)
                    vertices.Add(v);
                dict["Vertices"] = vertices;
                if (color is { } pc)
                    dict["C"] = ColorArray(pc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            case "Caret":
            {
                var r = RequireRect(rect);
                var dict = NewImportDict("Caret", r);
                if (color is { } cc)
                    dict["C"] = ColorArray(cc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            default:
                return null;
        }

        ApplyCommonEntries(created.RawDictionary, annot, contents, author, width);
        return (pageNumber, created.RawDictionary);
    }

    /// <summary>
    /// Apply the FDF common entries onto the attached dictionary — including
    /// onto dictionaries produced by the authoring methods, which generate
    /// their own /NM and /M that the FDF values must override so a round-trip
    /// preserves identity.
    /// </summary>
    private static void ApplyCommonEntries(
        PdfDictionary dict, PdfDictionary source, string? contents, string? author, double? width)
    {
        if (source.GetStringOrNull("NM") is { Length: > 0 } name)
            dict.SetString("NM", name);
        if (source.GetStringOrNull("M") is { Length: > 0 } date)
            dict.SetString("M", date);
        if (source.GetStringOrNull("CreationDate") is { Length: > 0 } creation)
            dict.SetString("CreationDate", creation);
        if (source.GetStringOrNull("Subj") is { Length: > 0 } subject)
            dict.SetString("Subj", subject);
        if (source.GetOptional("F") is { } flagsObj && flagsObj.TryGetNumber(out var flags))
            dict.SetInt("F", (int)flags);
        if (source.GetOptional("CA") is { } opacityObj && opacityObj.TryGetNumber(out var opacity))
            dict.SetNumber("CA", Math.Clamp(opacity, 0, 1));

        if (!string.IsNullOrEmpty(contents) && !dict.ContainsKey("Contents"))
            dict.SetString("Contents", contents);
        if (!string.IsNullOrWhiteSpace(author) && !dict.ContainsKey("T"))
            dict.SetString("T", author!);

        var sourceBs = source.GetDictionaryOrNull("BS");
        var style = sourceBs?.GetNameOrNull("S");
        var dashes = sourceBs?.GetArrayOrNull("D");
        if (width != null || style != null || dashes != null)
        {
            var bs = dict.GetDictionaryOrNull("BS");
            if (bs == null)
            {
                bs = new PdfDictionary();
                bs.SetName("Type", "Border");
                dict["BS"] = bs;
            }
            if (width != null)
                bs.SetNumber("W", width.Value);
            if (style != null)
                bs.SetName("S", style);
            else if (bs.GetNameOrNull("S") == null)
                bs.SetName("S", dashes != null ? "D" : "S");
            if (dashes is { Count: > 0 })
            {
                var d = new PdfArray();
                for (int i = 0; i < dashes.Count; i++)
                {
                    if (dashes[i].TryGetNumber(out var v))
                        d.Add(v);
                }
                bs["D"] = d;
            }
        }
    }

    private static PdfDictionary NewImportDict(string subtype, PdfRectangle rect)
    {
        var normalized = rect.Normalize();
        var dict = new PdfDictionary();
        dict.SetName("Type", "Annot");
        dict.SetName("Subtype", subtype);
        dict["Rect"] = PdfArray.FromRectangle(
            normalized.Left, normalized.Bottom, normalized.Right, normalized.Top);
        dict.SetInt("F", (int)PdfAnnotationFlags.Print);
        dict.SetString("NM", $"excise-{Guid.NewGuid():N}");
        return dict;
    }

    // ── Reading helpers (dictionaries are deep-resolved before use) ──────────

    private static PdfRectangle RequireRect(PdfRectangle? rect) =>
        rect ?? throw new FdfSkipException("missing /Rect entry");

    private static PdfRectangle? ReadRect(PdfDictionary annot)
    {
        var numbers = ReadNumbers(annot, "Rect");
        if (numbers is not { Count: >= 4 })
            return null;
        return new PdfRectangle(numbers[0], numbers[1], numbers[2], numbers[3]).Normalize();
    }

    private static (double, double, double)? ReadColor(PdfDictionary annot, string key)
    {
        var numbers = ReadNumbers(annot, key);
        if (numbers is not { Count: 3 })
            return null;
        return (Math.Clamp(numbers[0], 0, 1), Math.Clamp(numbers[1], 0, 1), Math.Clamp(numbers[2], 0, 1));
    }

    private static List<double>? ReadNumbers(PdfDictionary annot, string key)
    {
        if (annot.GetArrayOrNull(key) is not { } array)
            return null;
        var result = new List<double>(array.Count);
        foreach (var item in array)
        {
            if (item.TryGetNumber(out var v) && !double.IsNaN(v) && !double.IsInfinity(v))
                result.Add(v);
        }
        return result.Count > 0 ? result : null;
    }

    private static PdfRectangle BoundsOf(IReadOnlyList<double> flatPoints)
    {
        double minX = double.MaxValue, minY = double.MaxValue;
        double maxX = double.MinValue, maxY = double.MinValue;
        for (int i = 0; i + 1 < flatPoints.Count; i += 2)
        {
            minX = Math.Min(minX, flatPoints[i]);
            maxX = Math.Max(maxX, flatPoints[i]);
            minY = Math.Min(minY, flatPoints[i + 1]);
            maxY = Math.Max(maxY, flatPoints[i + 1]);
        }
        return new PdfRectangle(minX, minY, maxX, maxY);
    }

    private static PdfArray ReadQuadPointsOrDefault(PdfDictionary annot, PdfRectangle rect)
    {
        var coords = ReadNumbers(annot, "QuadPoints");
        var arr = new PdfArray();
        if (coords is { Count: >= 8 } && coords.Count % 8 == 0)
        {
            foreach (var v in coords)
                arr.Add(v);
            return arr;
        }

        // Derive a single quad from the rect (top-left, top-right,
        // bottom-left, bottom-right — §12.5.6.10 conventions).
        arr.Add(rect.Left);
        arr.Add(rect.Top);
        arr.Add(rect.Right);
        arr.Add(rect.Top);
        arr.Add(rect.Left);
        arr.Add(rect.Bottom);
        arr.Add(rect.Right);
        arr.Add(rect.Bottom);
        return arr;
    }

    private static List<IReadOnlyList<(double X, double Y)>> ReadInkList(PdfDictionary annot)
    {
        var strokes = new List<IReadOnlyList<(double X, double Y)>>();
        if (annot.GetArrayOrNull("InkList") is not { } inkList)
            return strokes;

        foreach (var entry in inkList)
        {
            if (entry is not PdfArray gesture)
                continue;
            var numbers = new List<double>(gesture.Count);
            foreach (var item in gesture)
            {
                if (item.TryGetNumber(out var v) && !double.IsNaN(v) && !double.IsInfinity(v))
                    numbers.Add(v);
            }
            var stroke = new List<(double X, double Y)>(numbers.Count / 2);
            for (int i = 0; i + 1 < numbers.Count; i += 2)
                stroke.Add((numbers[i], numbers[i + 1]));
            if (stroke.Count >= 2)
                strokes.Add(stroke);
        }
        return strokes;
    }

    private static ((double R, double G, double B), double FontSize) ParseDefaultAppearance(string? da)
    {
        (double R, double G, double B) color = (0, 0, 0);
        double fontSize = 12;
        if (string.IsNullOrWhiteSpace(da))
            return (color, fontSize);

        var rgb = Regex.Match(da, @"([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+rg\b");
        if (rgb.Success &&
            TryParseNumber(rgb.Groups[1].Value, out var r) &&
            TryParseNumber(rgb.Groups[2].Value, out var g) &&
            TryParseNumber(rgb.Groups[3].Value, out var b))
        {
            color = (Math.Clamp(r, 0, 1), Math.Clamp(g, 0, 1), Math.Clamp(b, 0, 1));
        }
        else
        {
            var gray = Regex.Match(da, @"([\d.]+)\s+g\b");
            if (gray.Success && TryParseNumber(gray.Groups[1].Value, out var v))
            {
                v = Math.Clamp(v, 0, 1);
                color = (v, v, v);
            }
        }

        var tf = Regex.Match(da, @"/\S+\s+([\d.]+)\s+Tf\b");
        if (tf.Success && TryParseNumber(tf.Groups[1].Value, out var size) && size > 0)
            fontSize = size;

        return (color, fontSize);
    }

    private static bool TryParseNumber(string? raw, out double value) =>
        double.TryParse(raw, System.Globalization.NumberStyles.Float,
            System.Globalization.CultureInfo.InvariantCulture, out value)
        && !double.IsNaN(value) && !double.IsInfinity(value);

    private static PdfArray ColorArray((double R, double G, double B) color) =>
        new(new PdfReal(color.R), new PdfReal(color.G), new PdfReal(color.B));

    private static void SetString(PdfDictionary dict, string key, string? value)
    {
        if (!string.IsNullOrEmpty(value))
            dict.SetString(key, value);
    }

    private static PdfArray CopyNumberArray(PdfArray source)
    {
        var copy = new PdfArray();
        for (int i = 0; i < source.Count; i++)
        {
            if (source[i].TryGetNumber(out var v))
                copy.Add(v);
        }
        return copy;
    }

    // ── Raw-dictionary helpers (resolve indirect references) ──────────────────

    private static PdfArray? ResolveArray(PdfDocument document, PdfDictionary dict, string key) =>
        dict.GetOptional(key) is { } obj && document.Resolve(obj) is PdfArray arr ? arr : null;

    private static string? ResolveString(PdfDocument document, PdfDictionary dict, string key) =>
        dict.GetOptional(key) is { } obj && document.Resolve(obj) is PdfString s ? s.Value : null;

    private static double? ResolveNumber(PdfDocument document, PdfDictionary dict, string key) =>
        dict.GetOptional(key) is { } obj && document.Resolve(obj).TryGetNumber(out var v) ? v : null;
}
