using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;
using Excise.Core.Document;
using Excise.Core.Primitives;

namespace Excise.Core.Forms;

/// <summary>
/// Result of importing an XFDF annotation file into a document.
/// </summary>
public sealed class XfdfImportResult
{
    /// <summary>The annotations that were added to the document, re-read from their pages.</summary>
    public IReadOnlyList<PdfAnnotation> Imported { get; }

    /// <summary>
    /// Human-readable descriptions of XFDF elements that were present but not
    /// imported (unsupported subtype, missing required geometry, page out of
    /// range). Empty when everything was imported.
    /// </summary>
    public IReadOnlyList<string> Skipped { get; }

    internal XfdfImportResult(IReadOnlyList<PdfAnnotation> imported, IReadOnlyList<string> skipped)
    {
        Imported = imported;
        Skipped = skipped;
    }
}

/// <summary>
/// XFDF (XML Forms Data Format) annotation import/export — the interchange
/// format Acrobat, Foxit and other reviewers use for "Export comments as data
/// file" workflows (#626). Grammar follows the Adobe XFDF 3.0 specification
/// (the basis of ISO 19444-1): an <c>&lt;xfdf&gt;</c> root in the
/// <c>http://ns.adobe.com/xfdf/</c> namespace with an <c>&lt;annots&gt;</c>
/// child holding one element per annotation, named after the lowercased PDF
/// subtype (<c>highlight</c>, <c>square</c>, <c>ink</c>, …).
/// </summary>
/// <remarks>
/// <para>
/// <b>Export</b> covers every markup/geometry subtype the reader surfaces:
/// Text, FreeText, Line, Square, Circle, Polygon, PolyLine, Highlight,
/// Underline, Squiggly, StrikeOut, Stamp, Caret, Ink, Watermark and Redact.
/// Link, Popup, Widget, FileAttachment, Sound, Movie and Screen annotations
/// are not exported — links and widgets are document structure (widgets belong
/// to the XFDF <c>&lt;fields&gt;</c> form-data section, not to comments), and
/// popups are regenerated by the consuming viewer.
/// </para>
/// <para>
/// <b>Import</b> supports text, freetext, line, square, circle, polygon,
/// polyline, highlight, underline, squiggly, strikeout, caret and ink
/// elements. Subtypes with an authoring method
/// (<see cref="PdfAnnotationAuthoring"/>) are created through it so they get
/// a baked <c>/AP</c> appearance stream; the remainder are written as
/// spec-correct dictionaries without an appearance (viewers synthesize one,
/// as they do for Acrobat's own AP-less markup). Unknown elements are
/// reported in <see cref="XfdfImportResult.Skipped"/>, never an error.
/// </para>
/// </remarks>
public static class XfdfSerializer
{
    /// <summary>The XFDF XML namespace (Adobe XFDF 3.0 §"XFDF namespace").</summary>
    public const string XfdfNamespace = "http://ns.adobe.com/xfdf/";

    private static readonly XNamespace Ns = XfdfNamespace;

    // ── Export ────────────────────────────────────────────────────────────────

    /// <summary>
    /// Serialize all exportable annotations of <paramref name="document"/> to
    /// an XFDF string (UTF-8 declaration, indented).
    /// </summary>
    public static string ExportAnnotations(PdfDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var xdoc = BuildXfdf(document);
        var settings = new XmlWriterSettings
        {
            Indent = true,
            Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            OmitXmlDeclaration = false
        };

        var sb = new StringBuilder();
        using (var writer = XmlWriter.Create(sb, settings))
            xdoc.Save(writer);

        // StringBuilder-backed XmlWriter declares encoding="utf-16"; the
        // canonical XFDF declaration is UTF-8 (and the Stream overload really
        // writes UTF-8 bytes).
        return sb.ToString().Replace("encoding=\"utf-16\"", "encoding=\"utf-8\"");
    }

    /// <summary>
    /// Serialize all exportable annotations of <paramref name="document"/> as
    /// UTF-8 XFDF to <paramref name="output"/>. The stream is left open.
    /// </summary>
    public static void ExportAnnotations(PdfDocument document, Stream output)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(output);

        var xdoc = BuildXfdf(document);
        var settings = new XmlWriterSettings
        {
            Indent = true,
            Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            CloseOutput = false
        };
        using var writer = XmlWriter.Create(output, settings);
        xdoc.Save(writer);
    }

    private static XDocument BuildXfdf(PdfDocument document)
    {
        var annots = new XElement(Ns + "annots");

        int pageIndex = 0;
        foreach (var page in document.GetPages())
        {
            foreach (var annotation in page.GetAnnotations())
            {
                var element = ExportOne(document, annotation, pageIndex);
                if (element != null)
                    annots.Add(element);
            }
            pageIndex++;
        }

        var root = new XElement(Ns + "xfdf",
            new XAttribute(XNamespace.Xml + "space", "preserve"),
            annots);

        return new XDocument(new XDeclaration("1.0", "UTF-8", null), root);
    }

    private static XElement? ExportOne(PdfDocument document, PdfAnnotation a, int pageIndex)
    {
        var elementName = a.Subtype switch
        {
            PdfAnnotationSubtype.Text      => "text",
            PdfAnnotationSubtype.FreeText  => "freetext",
            PdfAnnotationSubtype.Line      => "line",
            PdfAnnotationSubtype.Square    => "square",
            PdfAnnotationSubtype.Circle    => "circle",
            PdfAnnotationSubtype.Polygon   => "polygon",
            PdfAnnotationSubtype.PolyLine  => "polyline",
            PdfAnnotationSubtype.Highlight => "highlight",
            PdfAnnotationSubtype.Underline => "underline",
            PdfAnnotationSubtype.Squiggly  => "squiggly",
            PdfAnnotationSubtype.StrikeOut => "strikeout",
            PdfAnnotationSubtype.Stamp     => "stamp",
            PdfAnnotationSubtype.Caret     => "caret",
            PdfAnnotationSubtype.Ink       => "ink",
            PdfAnnotationSubtype.Watermark => "watermark",
            PdfAnnotationSubtype.Redact    => "redact",
            _ => null // Link/Popup/Widget/FileAttachment/Sound/Movie/Screen/Unknown
        };
        if (elementName == null)
            return null;

        var el = new XElement(Ns + elementName);
        var dict = a.RawDictionary;

        el.SetAttributeValue("page", pageIndex);
        el.SetAttributeValue("rect", FormatNumbers(",", a.Rect.Left, a.Rect.Bottom, a.Rect.Right, a.Rect.Top));

        if (a.Color is { } c)
            el.SetAttributeValue("color", FormatHexColor(c.R, c.G, c.B));
        if (ResolveArray(document, dict, "IC") is { Count: 3 } ic)
            el.SetAttributeValue("interior-color",
                FormatHexColor(ic.GetNumber(0), ic.GetNumber(1), ic.GetNumber(2)));

        if (a.Flags != PdfAnnotationFlags.None)
            el.SetAttributeValue("flags", FormatFlags(a.Flags));

        SetStringAttribute(el, "name", a.Name);
        SetStringAttribute(el, "title", a.Author);
        SetStringAttribute(el, "subject", ResolveString(document, dict, "Subj"));
        SetStringAttribute(el, "date", ResolveString(document, dict, "M"));
        SetStringAttribute(el, "creationdate", ResolveString(document, dict, "CreationDate"));

        if (ResolveNumber(document, dict, "CA") is { } opacity)
            el.SetAttributeValue("opacity", FormatNumber(opacity));

        if (a.BorderWidth is { } width)
            el.SetAttributeValue("width", FormatNumber(width));
        if (BorderStyleToXfdf(a.BorderStyle) is { } style)
            el.SetAttributeValue("style", style);
        if (a.BorderDashPattern is { Count: > 0 } dashes)
            el.SetAttributeValue("dashes", string.Join(",", dashes.Select(FormatNumber)));

        // ── Subtype-specific geometry ─────────────────────────────────────────

        if (a.IsTextMarkup || a.Subtype == PdfAnnotationSubtype.Redact)
        {
            // Raw /QuadPoints keeps the exact 8-number quads (the read model
            // collapses them to bounding boxes).
            if (ResolveArray(document, dict, "QuadPoints") is { Count: >= 8 } qp)
                el.SetAttributeValue("coords",
                    string.Join(",", Enumerable.Range(0, qp.Count).Select(i => FormatNumber(qp.GetNumber(i)))));
        }

        if (a.LineEndpoints is { } line)
        {
            el.SetAttributeValue("start", FormatNumbers(",", line.X1, line.Y1));
            el.SetAttributeValue("end", FormatNumbers(",", line.X2, line.Y2));
        }

        if (a.Vertices is { Count: > 0 } vertices)
            el.SetAttributeValue("vertices",
                string.Join(";", vertices.Select(v => FormatNumbers(",", v.X, v.Y))));

        if (a.InkStrokes is { Count: > 0 } strokes)
        {
            var inklist = new XElement(Ns + "inklist");
            foreach (var stroke in strokes)
                inklist.Add(new XElement(Ns + "gesture",
                    string.Join(";", stroke.Select(p => FormatNumbers(",", p.X, p.Y)))));
            el.Add(inklist);
        }

        if (a.Subtype == PdfAnnotationSubtype.Text)
        {
            SetStringAttribute(el, "icon", a.IconName);
            el.SetAttributeValue("open", a.IsOpen ? "yes" : "no");
        }
        else if (a.Subtype == PdfAnnotationSubtype.Stamp)
        {
            SetStringAttribute(el, "icon", a.IconName);
        }

        if (a.Subtype == PdfAnnotationSubtype.FreeText)
        {
            if (dict.GetInt("Q", 0) is var q and > 0)
                el.SetAttributeValue("justification", q == 1 ? "centered" : "right");
            if (ResolveString(document, dict, "DA") is { } da)
                el.Add(new XElement(Ns + "defaultappearance", SanitizeXmlText(da)));
        }

        if (!string.IsNullOrEmpty(a.Contents))
            el.Add(new XElement(Ns + "contents", SanitizeXmlText(a.Contents)));

        return el;
    }

    // ── Import ────────────────────────────────────────────────────────────────

    /// <summary>
    /// Parse <paramref name="xfdf"/> and add the annotations it describes to
    /// <paramref name="document"/>.
    /// </summary>
    /// <exception cref="XmlException">The input is not well-formed XML.</exception>
    /// <exception cref="InvalidDataException">The XML is not an XFDF document
    /// (root element is not <c>xfdf</c>).</exception>
    public static XfdfImportResult ImportAnnotations(PdfDocument document, string xfdf)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(xfdf);

        return ImportCore(document, XDocument.Parse(xfdf));
    }

    /// <summary>
    /// Parse XFDF from <paramref name="input"/> and add the annotations it
    /// describes to <paramref name="document"/>. The stream is left open.
    /// </summary>
    /// <exception cref="XmlException">The input is not well-formed XML.</exception>
    /// <exception cref="InvalidDataException">The XML is not an XFDF document
    /// (root element is not <c>xfdf</c>).</exception>
    public static XfdfImportResult ImportAnnotations(PdfDocument document, Stream input)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(input);

        return ImportCore(document, XDocument.Load(input));
    }

    private static XfdfImportResult ImportCore(PdfDocument document, XDocument xdoc)
    {
        var root = xdoc.Root;
        if (root == null || !string.Equals(root.Name.LocalName, "xfdf", StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException(
                $"Not an XFDF document: root element is <{root?.Name.LocalName ?? "(none)"}>, expected <xfdf>.");

        var skipped = new List<string>();
        var added = new List<(int PageNumber, PdfDictionary Dictionary)>();

        var annots = root.Elements().FirstOrDefault(e => e.Name.LocalName == "annots");
        if (annots != null)
        {
            foreach (var el in annots.Elements())
            {
                var localName = el.Name.LocalName;
                try
                {
                    var result = ImportOne(document, el, localName);
                    if (result is { } ok)
                        added.Add(ok);
                    else
                        skipped.Add(DescribeSkip(el, localName, "unsupported annotation type"));
                }
                catch (XfdfSkipException skip)
                {
                    skipped.Add(DescribeSkip(el, localName, skip.Message));
                }
            }
        }

        // Re-read the freshly attached annotations so the returned models
        // reflect every entry (NM, dates, flags) applied after authoring.
        var imported = new List<PdfAnnotation>(added.Count);
        foreach (var pageGroup in added.GroupBy(x => x.PageNumber))
        {
            var pageAnnotations = document.GetPage(pageGroup.Key).GetAnnotations();
            foreach (var (_, dictionary) in pageGroup)
            {
                var model = pageAnnotations.FirstOrDefault(x => ReferenceEquals(x.RawDictionary, dictionary));
                if (model != null)
                    imported.Add(model);
            }
        }

        return new XfdfImportResult(imported, skipped);
    }

    private static string DescribeSkip(XElement el, string localName, string reason)
    {
        var name = el.Attribute("name")?.Value;
        return name == null ? $"{localName}: {reason}" : $"{localName} \"{name}\": {reason}";
    }

    /// <summary>Signals that a single XFDF element cannot be imported (recorded, not fatal).</summary>
    private sealed class XfdfSkipException(string message) : Exception(message);

    private static (int PageNumber, PdfDictionary Dictionary)? ImportOne(
        PdfDocument document, XElement el, string localName)
    {
        // Common attributes (XFDF 3.0, common annotation attributes).
        int pageIndex = ParseIntAttribute(el, "page") ?? 0;
        int pageNumber = pageIndex + 1;
        if (pageNumber < 1 || pageNumber > document.Pages.Count)
            throw new XfdfSkipException($"page {pageIndex} out of range (document has {document.Pages.Count} pages)");

        var rect = ParseRectAttribute(el);
        var color = ParseHexColorAttribute(el, "color");
        var interior = ParseHexColorAttribute(el, "interior-color");
        var contents = ChildText(el, "contents");
        var author = el.Attribute("title")?.Value;
        double? width = ParseNumberAttribute(el, "width");

        PdfAnnotation created;
        switch (localName)
        {
            case "text":
            {
                var r = RequireRect(rect);
                var icon = el.Attribute("icon")?.Value;
                bool open = string.Equals(el.Attribute("open")?.Value, "yes", StringComparison.OrdinalIgnoreCase);
                if (!string.IsNullOrWhiteSpace(contents))
                {
                    created = document.AddTextAnnotation(
                        pageNumber, r, contents!, author, open,
                        string.IsNullOrWhiteSpace(icon) ? "Note" : icon!);
                }
                else
                {
                    var dict = NewImportDict("Text", r);
                    dict.SetBool("Open", open);
                    dict.SetName("Name", string.IsNullOrWhiteSpace(icon) ? "Note" : icon!);
                    created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                }
                if (color is { } tc)
                    created.RawDictionary["C"] = ColorArray(tc);
                break;
            }

            case "square":
            case "circle":
            {
                var r = RequireRect(rect);
                bool isCircle = localName == "circle";
                var stroke = color ?? (1, 0, 0);
                double borderWidth = width ?? 1;
                if (borderWidth > 0 || interior != null)
                {
                    created = isCircle
                        ? document.AddCircleAnnotation(
                            pageNumber, r, contents, author,
                            stroke.Item1, stroke.Item2, stroke.Item3, borderWidth,
                            interior?.Item1, interior?.Item2, interior?.Item3)
                        : document.AddSquareAnnotation(
                            pageNumber, r, contents, author,
                            stroke.Item1, stroke.Item2, stroke.Item3, borderWidth,
                            interior?.Item1, interior?.Item2, interior?.Item3);
                }
                else
                {
                    // Zero border and no fill: legal but invisible — keep the
                    // data without an appearance stream.
                    var dict = NewImportDict(isCircle ? "Circle" : "Square", r);
                    dict["C"] = ColorArray(stroke);
                    created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                }
                break;
            }

            case "freetext":
            {
                var r = RequireRect(rect);
                if (string.IsNullOrWhiteSpace(contents))
                    throw new XfdfSkipException("freetext without <contents> text");

                var (textColor, fontSize) = ParseDefaultAppearance(ChildText(el, "defaultappearance"));
                var quadding = ParseJustification(el.Attribute("justification")?.Value);
                created = document.AddFreeTextAnnotation(
                    pageNumber, r, contents!, author, fontSize,
                    textColor.R, textColor.G, textColor.B, quadding,
                    borderWidth: width ?? 0,
                    backgroundRed: color?.Item1,
                    backgroundGreen: color?.Item2,
                    backgroundBlue: color?.Item3);
                break;
            }

            case "ink":
            {
                var strokes = ParseInkGestures(el);
                if (strokes.Count == 0)
                    throw new XfdfSkipException("ink without a usable <inklist> gesture");
                var stroke = color ?? (0, 0, 0);
                created = document.AddInkAnnotation(
                    pageNumber, strokes, contents, author,
                    stroke.Item1, stroke.Item2, stroke.Item3, width ?? 2);
                break;
            }

            case "highlight":
            case "underline":
            case "squiggly":
            case "strikeout":
            {
                var r = RequireRect(rect);
                var subtype = localName switch
                {
                    "highlight" => "Highlight",
                    "underline" => "Underline",
                    "squiggly"  => "Squiggly",
                    _           => "StrikeOut"
                };
                var dict = NewImportDict(subtype, r);
                dict["QuadPoints"] = ParseCoordsOrDefault(el, r);
                if (color is { } mc)
                    dict["C"] = ColorArray(mc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            case "line":
            {
                var start = ParseNumberListAttribute(el, "start");
                var end = ParseNumberListAttribute(el, "end");
                if (start is not { Count: >= 2 } || end is not { Count: >= 2 })
                    throw new XfdfSkipException("line without start/end attributes");
                var r = rect ?? new PdfRectangle(
                    Math.Min(start[0], end[0]), Math.Min(start[1], end[1]),
                    Math.Max(start[0], end[0]), Math.Max(start[1], end[1]));
                var dict = NewImportDict("Line", r);
                dict["L"] = new PdfArray(
                    new PdfReal(start[0]), new PdfReal(start[1]),
                    new PdfReal(end[0]), new PdfReal(end[1]));
                if (color is { } lc)
                    dict["C"] = ColorArray(lc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            case "polygon":
            case "polyline":
            {
                var points = ParseNumberListAttribute(el, "vertices");
                if (points is not { Count: >= 4 })
                    throw new XfdfSkipException($"{localName} without a vertices attribute");
                var r = rect ?? BoundsOf(points);
                var dict = NewImportDict(localName == "polygon" ? "Polygon" : "PolyLine", r);
                var vertices = new PdfArray();
                foreach (var v in points)
                    vertices.Add(v);
                dict["Vertices"] = vertices;
                if (color is { } pc)
                    dict["C"] = ColorArray(pc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            case "caret":
            {
                var r = RequireRect(rect);
                var dict = NewImportDict("Caret", r);
                if (color is { } cc)
                    dict["C"] = ColorArray(cc);
                created = PdfAnnotationAuthoring.AttachImported(document, pageNumber, dict);
                break;
            }

            default:
                return null;
        }

        ApplyCommonEntries(created.RawDictionary, el, contents, author, width);
        return (pageNumber, created.RawDictionary);
    }

    /// <summary>
    /// Apply the XFDF common attributes onto the attached dictionary —
    /// including onto dictionaries produced by the authoring methods, which
    /// generate their own /NM and /M that the XFDF values must override so a
    /// round-trip preserves identity.
    /// </summary>
    private static void ApplyCommonEntries(
        PdfDictionary dict, XElement el, string? contents, string? author, double? width)
    {
        if (el.Attribute("name")?.Value is { Length: > 0 } name)
            dict.SetString("NM", name);
        if (el.Attribute("date")?.Value is { Length: > 0 } date)
            dict.SetString("M", date);
        if (el.Attribute("creationdate")?.Value is { Length: > 0 } creation)
            dict.SetString("CreationDate", creation);
        if (el.Attribute("subject")?.Value is { Length: > 0 } subject)
            dict.SetString("Subj", subject);
        if (ParseFlagsAttribute(el) is { } flags)
            dict.SetInt("F", (int)flags);
        if (ParseNumberAttribute(el, "opacity") is { } opacity)
            dict.SetNumber("CA", Math.Clamp(opacity, 0, 1));

        if (!string.IsNullOrEmpty(contents) && !dict.ContainsKey("Contents"))
            dict.SetString("Contents", contents);
        if (!string.IsNullOrWhiteSpace(author) && !dict.ContainsKey("T"))
            dict.SetString("T", author!);

        var style = XfdfToBorderStyle(el.Attribute("style")?.Value);
        var dashes = ParseNumberListAttribute(el, "dashes");
        if (width != null || style != null || dashes != null)
        {
            var bs = dict.GetDictionaryOrNull("BS");
            if (bs == null)
            {
                bs = new PdfDictionary();
                bs.SetName("Type", "Border");
                dict["BS"] = bs;
            }
            if (width != null)
                bs.SetNumber("W", width.Value);
            if (style != null)
                bs.SetName("S", style);
            else if (bs.GetNameOrNull("S") == null)
                bs.SetName("S", dashes != null ? "D" : "S");
            if (dashes is { Count: > 0 })
            {
                var d = new PdfArray();
                foreach (var v in dashes)
                    d.Add(v);
                bs["D"] = d;
            }
        }
    }

    private static PdfDictionary NewImportDict(string subtype, PdfRectangle rect)
    {
        var normalized = rect.Normalize();
        var dict = new PdfDictionary();
        dict.SetName("Type", "Annot");
        dict.SetName("Subtype", subtype);
        dict["Rect"] = PdfArray.FromRectangle(
            normalized.Left, normalized.Bottom, normalized.Right, normalized.Top);
        dict.SetInt("F", (int)PdfAnnotationFlags.Print);
        dict.SetString("NM", $"excise-{Guid.NewGuid():N}");
        return dict;
    }

    // ── Parsing helpers ───────────────────────────────────────────────────────

    private static PdfRectangle RequireRect(PdfRectangle? rect) =>
        rect ?? throw new XfdfSkipException("missing rect attribute");

    private static PdfRectangle? ParseRectAttribute(XElement el)
    {
        var numbers = ParseNumberListAttribute(el, "rect");
        if (numbers is not { Count: >= 4 })
            return null;
        return new PdfRectangle(numbers[0], numbers[1], numbers[2], numbers[3]).Normalize();
    }

    private static PdfRectangle BoundsOf(IReadOnlyList<double> flatPoints)
    {
        double minX = double.MaxValue, minY = double.MaxValue;
        double maxX = double.MinValue, maxY = double.MinValue;
        for (int i = 0; i + 1 < flatPoints.Count; i += 2)
        {
            minX = Math.Min(minX, flatPoints[i]);
            maxX = Math.Max(maxX, flatPoints[i]);
            minY = Math.Min(minY, flatPoints[i + 1]);
            maxY = Math.Max(maxY, flatPoints[i + 1]);
        }
        return new PdfRectangle(minX, minY, maxX, maxY);
    }

    private static PdfArray ParseCoordsOrDefault(XElement el, PdfRectangle rect)
    {
        var coords = ParseNumberListAttribute(el, "coords");
        var arr = new PdfArray();
        if (coords is { Count: >= 8 } && coords.Count % 8 == 0)
        {
            foreach (var v in coords)
                arr.Add(v);
            return arr;
        }

        // Derive a single quad from the rect (top-left, top-right,
        // bottom-left, bottom-right — §12.5.6.10 conventions).
        arr.Add(rect.Left);
        arr.Add(rect.Top);
        arr.Add(rect.Right);
        arr.Add(rect.Top);
        arr.Add(rect.Left);
        arr.Add(rect.Bottom);
        arr.Add(rect.Right);
        arr.Add(rect.Bottom);
        return arr;
    }

    private static List<IReadOnlyList<(double X, double Y)>> ParseInkGestures(XElement el)
    {
        var strokes = new List<IReadOnlyList<(double X, double Y)>>();
        var inklist = el.Elements().FirstOrDefault(e => e.Name.LocalName == "inklist");
        if (inklist == null)
            return strokes;

        foreach (var gesture in inklist.Elements().Where(e => e.Name.LocalName == "gesture"))
        {
            var numbers = ParseNumberList(gesture.Value);
            var stroke = new List<(double X, double Y)>(numbers.Count / 2);
            for (int i = 0; i + 1 < numbers.Count; i += 2)
                stroke.Add((numbers[i], numbers[i + 1]));
            if (stroke.Count >= 2)
                strokes.Add(stroke);
        }
        return strokes;
    }

    private static ((double R, double G, double B), double FontSize) ParseDefaultAppearance(string? da)
    {
        (double R, double G, double B) color = (0, 0, 0);
        double fontSize = 12;
        if (string.IsNullOrWhiteSpace(da))
            return (color, fontSize);

        var rgb = Regex.Match(da, @"([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+rg\b");
        if (rgb.Success &&
            TryParseNumber(rgb.Groups[1].Value, out var r) &&
            TryParseNumber(rgb.Groups[2].Value, out var g) &&
            TryParseNumber(rgb.Groups[3].Value, out var b))
        {
            color = (Math.Clamp(r, 0, 1), Math.Clamp(g, 0, 1), Math.Clamp(b, 0, 1));
        }
        else
        {
            var gray = Regex.Match(da, @"([\d.]+)\s+g\b");
            if (gray.Success && TryParseNumber(gray.Groups[1].Value, out var v))
            {
                v = Math.Clamp(v, 0, 1);
                color = (v, v, v);
            }
        }

        var tf = Regex.Match(da, @"/\S+\s+([\d.]+)\s+Tf\b");
        if (tf.Success && TryParseNumber(tf.Groups[1].Value, out var size) && size > 0)
            fontSize = size;

        return (color, fontSize);
    }

    private static PdfFreeTextQuadding ParseJustification(string? value) => value?.Trim().ToLowerInvariant() switch
    {
        "centered" or "center" or "1" => PdfFreeTextQuadding.Centered,
        "right" or "2"                => PdfFreeTextQuadding.RightJustified,
        _                             => PdfFreeTextQuadding.LeftJustified
    };

    private static readonly (PdfAnnotationFlags Flag, string Name)[] FlagNames =
    [
        (PdfAnnotationFlags.Invisible,      "invisible"),
        (PdfAnnotationFlags.Hidden,         "hidden"),
        (PdfAnnotationFlags.Print,          "print"),
        (PdfAnnotationFlags.NoZoom,         "nozoom"),
        (PdfAnnotationFlags.NoRotate,       "norotate"),
        (PdfAnnotationFlags.NoView,         "noview"),
        (PdfAnnotationFlags.ReadOnly,       "readonly"),
        (PdfAnnotationFlags.Locked,         "locked"),
        (PdfAnnotationFlags.ToggleNoView,   "togglenoview"),
        (PdfAnnotationFlags.LockedContents, "lockedcontents")
    ];

    private static string FormatFlags(PdfAnnotationFlags flags) =>
        string.Join(",", FlagNames.Where(f => flags.HasFlag(f.Flag)).Select(f => f.Name));

    private static PdfAnnotationFlags? ParseFlagsAttribute(XElement el)
    {
        var raw = el.Attribute("flags")?.Value;
        if (string.IsNullOrWhiteSpace(raw))
            return null;

        var flags = PdfAnnotationFlags.None;
        foreach (var token in raw.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var match = FlagNames.FirstOrDefault(f =>
                string.Equals(f.Name, token, StringComparison.OrdinalIgnoreCase));
            if (match.Name != null)
                flags |= match.Flag;
        }
        return flags;
    }

    private static string? BorderStyleToXfdf(string? pdfStyle) => pdfStyle switch
    {
        "S" => "solid",
        "D" => "dash",
        "B" => "bevelled",
        "I" => "inset",
        "U" => "underline",
        _   => null
    };

    private static string? XfdfToBorderStyle(string? xfdfStyle) => xfdfStyle?.Trim().ToLowerInvariant() switch
    {
        "solid"                  => "S",
        "dash"                   => "D",
        "bevelled" or "beveled"  => "B",
        "inset"                  => "I",
        "underline"              => "U",
        _                        => null
    };

    private static (double, double, double)? ParseHexColorAttribute(XElement el, string attribute)
    {
        var raw = el.Attribute(attribute)?.Value?.Trim();
        if (raw is not { Length: 7 } || raw[0] != '#')
            return null;
        if (!int.TryParse(raw.AsSpan(1), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var rgb))
            return null;
        return (((rgb >> 16) & 0xFF) / 255.0, ((rgb >> 8) & 0xFF) / 255.0, (rgb & 0xFF) / 255.0);
    }

    private static string FormatHexColor(double r, double g, double b)
    {
        static int Channel(double v) => (int)Math.Clamp(Math.Round(v * 255), 0, 255);
        return $"#{Channel(r):X2}{Channel(g):X2}{Channel(b):X2}";
    }

    private static PdfArray ColorArray((double R, double G, double B) color) =>
        new(new PdfReal(color.R), new PdfReal(color.G), new PdfReal(color.B));

    private static int? ParseIntAttribute(XElement el, string attribute) =>
        int.TryParse(el.Attribute(attribute)?.Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)
            ? v : null;

    private static double? ParseNumberAttribute(XElement el, string attribute) =>
        TryParseNumber(el.Attribute(attribute)?.Value, out var v) ? v : null;

    private static IReadOnlyList<double>? ParseNumberListAttribute(XElement el, string attribute)
    {
        var raw = el.Attribute(attribute)?.Value;
        if (string.IsNullOrWhiteSpace(raw))
            return null;
        var numbers = ParseNumberList(raw);
        return numbers.Count > 0 ? numbers : null;
    }

    /// <summary>
    /// Parse a list of numbers from XFDF attribute/element text. Accepts the
    /// separators seen in the wild — commas within pairs, semicolons between
    /// pairs, and whitespace.
    /// </summary>
    private static List<double> ParseNumberList(string raw)
    {
        var result = new List<double>();
        foreach (var token in raw.Split([',', ';', ' ', '\t', '\r', '\n'], StringSplitOptions.RemoveEmptyEntries))
        {
            if (TryParseNumber(token, out var v))
                result.Add(v);
        }
        return result;
    }

    private static bool TryParseNumber(string? raw, out double value) =>
        double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out value)
        && !double.IsNaN(value) && !double.IsInfinity(value);

    private static string? ChildText(XElement el, string localName)
    {
        var child = el.Elements().FirstOrDefault(e => e.Name.LocalName == localName);
        return child?.Value;
    }

    // ── Raw-dictionary helpers (resolve indirect references) ──────────────────

    private static PdfArray? ResolveArray(PdfDocument document, PdfDictionary dict, string key) =>
        dict.GetOptional(key) is { } obj && document.Resolve(obj) is PdfArray arr ? arr : null;

    private static string? ResolveString(PdfDocument document, PdfDictionary dict, string key) =>
        dict.GetOptional(key) is { } obj && document.Resolve(obj) is PdfString s ? s.Value : null;

    private static double? ResolveNumber(PdfDocument document, PdfDictionary dict, string key) =>
        dict.GetOptional(key) is { } obj && document.Resolve(obj).TryGetNumber(out var v) ? v : null;

    // ── Formatting helpers ────────────────────────────────────────────────────

    private static string FormatNumber(double value) =>
        value.ToString("0.######", CultureInfo.InvariantCulture);

    private static string FormatNumbers(string separator, params double[] values) =>
        string.Join(separator, values.Select(FormatNumber));

    private static void SetStringAttribute(XElement el, string attribute, string? value)
    {
        if (!string.IsNullOrEmpty(value))
            el.SetAttributeValue(attribute, SanitizeXmlText(value));
    }

    /// <summary>
    /// Strip characters that are invalid in XML 1.0 (PDF strings may carry
    /// arbitrary control bytes); keeps tab/newline/carriage-return.
    /// </summary>
    private static string SanitizeXmlText(string value)
    {
        if (value.All(c => XmlConvert.IsXmlChar(c)))
            return value;
        return new string(value.Where(XmlConvert.IsXmlChar).ToArray());
    }
}
